### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by AIPTU3110** [CLADevs/VanillaX#10]
How to use this plugin? I have run the plugin in source and on phar, when it loads it doesn't work

**Comment by xXNiceYT** [comment]
You can run this with phar? If it doesn’t work, does it give u any error?

**Comment by AIPTU3110** [comment]
ErrorException: "scandir(phar:///root/pmmp/plugins/VanillaX.phar//src//entities/object): failed to open dir: operati
on failed" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/utils/Util
s" at line 23
ErrorException: "fopen(): SSL operation failed
 with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:ce
rtificate verify failed" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/scheduler/Downl
oadLootTableTask" at line 26

**Comment by xXNiceYT** [comment]
It’s probably you’re vps time change the vps timezone to America not sure if this is causing the issue
https://linuxize.com/post/how-to-set-or-change-timezone-on-ubuntu-20-04/ << for Ubuntu not sure what you are

**Comment by AIPTU3110** [comment]
Still not working, is there any other way?

**Comment by xXNiceYT** [comment]
Hmm I’ll recheck first one but the second one is something with you’re vps I’ll look into it later on sorry for those issues.

**Comment by Glyphs31** [comment]
How does this work? There is a loot table but the plugin is not enabled
ErrorException: "scandir(phar:///root/pmmp/plugins/VanillaX.phar/src//entities/object): failed to open dir: operation failed" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/utils/Utils" at line 24

**Comment by xXNiceYT** [comment]
Use the lastest version I’ve updated it. To fix that issue

**Comment by Glyphs31** [comment]
I've use latest version

**Comment by xXNiceYT** [comment]
> I've use latest version
https://poggit.pmmp.io/r/116396/VanillaX_dev-39.phar Try that

**Comment by Glyphs31** [comment]
i am using that version but it's still the same

**Comment by xXNiceYT** [comment]
> i am using that version but it's still the same

Is it unbuntuv7.4?

**Comment by Glyphs31** [comment]
I am in ubuntu and PHP 7.4

**Comment by xXNiceYT** [comment]
Hmm okay ima push this most likely should fix it.

**Comment by Glyphs31** [comment]
I've try new build and work nice thanks
