### ISSUE TITLE
Deactivating spawners in config does not work

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#106]
Please i can’t desactivate mobspaawner

**Comment by xXNiceYT** [comment]
Works fine for me, was any error caused? Due it being on

**Comment by SPMP2** [comment]
I have desactive with - 52 in config but already crash when i move in another world, console logs say me its mobs spawner can you send me your config, please 🥺

**Comment by xXNiceYT** [comment]
What’s the error?

**Comment by SPMP2** [comment]
I have found it thank s !
