### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#107]
Console logs : 

2021-09-13 [00:31:51] [Server thread/CRITICAL]: RuntimeException: "Expected a tag of type pocketmine\nbt\tag\IntTag, got pocketmine\nbt\tag\ByteTag" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 100
--
306 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(170): pocketmine\nbt\tag\CompoundTag->getTag(string[4] auto, string[25] pocketmine\nbt\tag\IntTag)
307 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #1 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(195): pocketmine\nbt\tag\CompoundTag->getTagValue(string[4] auto, string[25] pocketmine\nbt\tag\IntTag, NULL , boolean )
308 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #2 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/blocks/tile/CommandBlockTile(189): pocketmine\nbt\tag\CompoundTag->getInt(string[4] auto)
309 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/tile/Tile(167): CLADevs\VanillaX\blocks\tile\CommandBlockTile->readSaveData(object pocketmine\nbt\tag\CompoundTag)
310 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/tile/Spawnable(62): pocketmine\tile\Tile->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
311 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/tile/Tile(116): pocketmine\tile\Spawnable->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
312 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/format/Chunk(723): pocketmine\tile\Tile::createTile(string[12] CommandBlock, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
313 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/level/Level(2683): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
314 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/level/Level(2295): pocketmine\level\Level->loadChunk(integer 1, integer 3, boolean 1)
315 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/level/Level(2957): pocketmine\level\Level->getChunk(integer 1, integer 3, boolean 1)
316 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Player(1061): pocketmine\level\Level->populateChunk(integer 1, integer 3)
317 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Player(1857): pocketmine\Player->sendNextChunk()
318 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/Server(2399): pocketmine\Player->checkNetwork()
319 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
320 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
321 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
322 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
323 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
324 | 2021-09-13 [00:31:51] [Server thread/CRITICAL]: #18 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
325 | 2021-09-13 [00:31:51] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
326 | 2021-09-13 [00:31:51] [Server thread/EMERGENCY]: Please upload the "/home/gameserver/servers/serveur7/minecraftbedrock/crashdumps/Mon_Sep_13-00.31.51-CEST_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
327 | 2021-09-13 [00:31:51] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on

**Comment by xXNiceYT** [comment]
Do u had any other plugin that enabled commands block?

**Comment by xXNiceYT** [comment]
If so it’s because of that, I recommend disabling plugin and removing that command block and re-enabling plugin

**Comment by SPMP2** [comment]
No i haven’t enable command block but i have add : blockconverter and many block as converted on commandblock & i have put the java world (converted in bedrock) in default world, and i have that error i must desactivate command block in config like spawner ?

**Comment by xXNiceYT** [comment]
Alright

**Comment by SPMP2** [comment]
Ok i will try thank you for your fast answer !!🤩

**Comment by SPMP2** [comment]
Is working, thank you very mutch for the support of this plugin ! Very appreciable
