### ISSUE TITLE
VanillaX not loaded 

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#110]
2021-09-13 [11:31:05] [Server thread/CRITICAL]: ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 19, column 5), context while parsing a block mapping (line 3, column 1)" (EXCEPTION) in "pmsrc/src/pocketmine/utils/Config" at line 189
--
228 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[159] yaml_parse(): parsing error encountered during parsing: did not find expected ke, string[108] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src, integer 189, array[6])
229 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/utils/Config(189): yaml_parse(string[1296] ---.#If this is false entities(mobs, trident, fireworks, etc) will not register )
230 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/utils/Config(122): pocketmine\utils\Config->load(string[82] /home/gameserver/servers/serveur7/minecraftbedrock/plugin_data/VanillaX/config.y, integer -1, array[0])
231 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginBase(252): pocketmine\utils\Config->__construct(string[82] /home/gameserver/servers/serveur7/minecraftbedrock/plugin_data/VanillaX/config.y)
232 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/plugin/PluginBase(231): pocketmine\plugin\PluginBase->reloadConfig()
233 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #5 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager(44): pocketmine\plugin\PluginBase->getConfig()
234 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #6 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager(36): CLADevs\VanillaX\enchantments\EnchantmentManager->registerEnchantment(object CLADevs\VanillaX\enchantments\armors\BindingEnchantment)
235 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #7 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/utils/Utils(30): CLADevs\VanillaX\enchantments\EnchantmentManager->CLADevs\VanillaX\enchantments\{closure}(string[55] CLADevs\VanillaX\enchantments\armors\BindingEnchantment)
236 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #8 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/utils/Utils(25): CLADevs\VanillaX\utils\Utils::callDirectory(string[19] enchantments/armors, object Closure)
237 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #9 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager(38): CLADevs\VanillaX\utils\Utils::callDirectory(string[12] enchantments, object Closure)
238 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #10 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/VanillaX(52): CLADevs\VanillaX\enchantments\EnchantmentManager->startup()
239 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/plugin/PluginBase(116): CLADevs\VanillaX\VanillaX->onEnable()
240 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
241 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object CLADevs\VanillaX\VanillaX)
242 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object CLADevs\VanillaX\VanillaX)
243 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
244 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
245 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
246 | 2021-09-13 [11:31:05] [Server thread/CRITICAL]: #18 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)

**Comment by xXNiceYT** [comment]
You’re Config isn’t structured correctly

**Comment by SPMP2** [comment]
Thank you
