### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Momentariy** [CLADevs/VanillaX#113]
For bug pig!

Altay Crash Dump Sat Sep 18 21:07:27 UTC 2021

Error: Declaration of CLADevs\VanillaX\entities\passive\PigEntity::onInteract(CLADevs\VanillaX\entities\utils\EntityInteractResult $result): void must be compatible with pocketmine\entity\Living::onInteract(pocketmine\Player $player, pocketmine\item\Item $item, pocketmine\math\Vector3 $clickPos): bool
File: plugins/VanillaX.phar/src/CLADevs/VanillaX/entities/passive/PigEntity
Line: 65
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: VanillaX v2.2.0

Code:
[56]     public function getXpDropAmount(): int{
[57]         return $this->getLastHitByPlayer() ? mt_rand(1,3) : 0;
[58]     }
[59] 
[60]     public function saveNBT(): void{
[61]         $this->writeSaddle();
[62]         parent::saveNBT();
[63]     }
[64] 
[65]     public function onInteract(EntityInteractResult $result): void{
[66]         $player = $result->getPlayer();
[67]         $this->onButtonPressed(new InteractButtonResult($player, $result->getItem(), $player->getDataPropertyManager()->getString(self::DATA_INTERACTIVE_TAG)));
[68]     }
[69] 
[70]     public function onMouseHover(Player $player): void{
[71]         $this->recalculateButton($player, $player->getInventory()->getItemInHand());
[72]     }
[73] 
[74]     public function onSlotChange(Player $player, Item $old, Item $new): void{
[75]         if($old->getId() !== $new->getId()){

Backtrace:

Altay version: 3.22.1+dev [Protocol 448]
Git commit: 6ac6109e4e8a3326aa5eea83879171b31abab745
uname -a: Linux 937204a7-24a7-40ef-acfa-91fbee57f08c 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
PHP Version: 7.4.21
Zend version: 3.4.0
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- daverandom/callback-validator unknown@unknown
- pocketmine/binaryutils 0.1.13@0abee38d4e2861621f262c79a2a3d699d8a697f4
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.1.2@9757928424652393b178a3760073113aa7c9911b
- pocketmine/log 0.2.1@830b44a2cf96ef703c550abe64302f230231ca49
- pocketmine/log-pthreads 0.1.3@e477ecf6ec214fdd4415ea1da3fdd9d73bf699ea
- pocketmine/math 0.2.6@43057cb8c179a9859677b496a788db922fd5cfc3
- pocketmine/nbt 0.2.18@9f82ca4d7f97fcd9a566e44b63c4f18a7657ae82
- pocketmine/pocketmine-mp dev-1.13_altay@6ac6109e4e8a3326aa5eea83879171b31abab745
- pocketmine/raklib 0.12.11@9cce458b8bfde3e4dfdbf70c659fc7b7fe26b5c4
- pocketmine/snooze 0.1.5@70b5e7937a06878dd321a3182ceb76d56298f2cd
- pocketmine/spl 0.4.2@6b08b7cf8c4afa17139c9a1b3bf1b408531de161

Loaded plugins:
AdminTrollV2 1.2.1 by Rushil13579 for API(s) 3.0.0
AdvanceDeaths 1.5 by ErikX for API(s) 3.0.0
AdvancedKits 5.3.0 by luca28pet for API(s) 3.0.0
AdvancedPromo 1.0.0 by BenPlug for API(s) 3.0.0
AntiBot 1.0 by  for API(s) 3.0.0
AntiToolbox 1.0.0 by LittleAraaCute for API(s) 3.0.0
ArcRandomTP 1.1.1 by  for API(s) 3.0.0
Auth 1.0.0 by Denis Klyuyev for API(s) 3.0.0, 4.0.0
BanItem 2.3.3 by LDX for API(s) 3.0.0
BedcoreProtect 0.10.3 by matcracker for API(s) 3.21.0
BlazinJoin 1.1.5 by iiFlamiinBlaze for API(s) 3.0.0
BlusterySasha 1.0.1 by BlusterySasha for API(s) 3.0.0
BravoClan 1.2 by Itzdvbravo for API(s) 3.14.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
CB-Heads 3.0 by Wertzui123, Enes5519, Wertzui123 for API(s) 3.0.0
ChestShop 2.4.0 by MinecrafterJPN for API(s) 3.0.0
ClearPlayer 1.0.0 by radondev for API(s) 3.0.0
Craft 0.0.1 by MajorWaffles69 for API(s) 3.11.6
Crossbow 1.0.2 by alvin0319 for API(s) 3.0.0
CustomFishing 1.0.0-beta by YaN for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
DevTools 1.14.2 by PocketMine Team for API(s) 3.13.0
DynamicFT 1.0.5-dev2 by OguzhanUmutlu for API(s) 3.0.0
EasyModeration 1.0.0 by Rushil13579 for API(s) 3.0.0
EasyRepairItems 1.1.0 by GodWeedZao for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
ExtraGL 1.4 by FaigerSYS for API(s) 3.0.0
FlyPE 3.8.3 by AGTHARN for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
Friends 1.0.0 by BenPlug for API(s) 3.0.0
Godmode 1.0.0 by Vazzi for API(s) 3.22.1
HealthTag 2.0.2 by Shelly7w7 for API(s) 3.0.0
IgnorePlayer 1.1.0 by Rushil13579 for API(s) 3.0.0
InvCrashFix 0.0.1 by  for API(s) 3.14.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
ItemID 1.0.0 by HannesTheDev for API(s) 3.0.0
KygekJoinUI 1.5.1 by Kygekraqmak for API(s) 3.0.0
KygekRanksUI 1.3.0 by Kygekraqmak for API(s) 3.0.0
KygekRulesUI 1.2.0 by Kygekraqmak for API(s) 3.0.0
MagicTelePortal 1.3.4 by aliuly for API(s) 3.0.0
MineReset 3.3.0 by Falk for API(s) 3.0.0, 4.0.0
MineResetAuto 1.0.0 by JonyGamesYT9 for API(s) 3.0.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
NewMenu 0.0.1 by NewPlugin for API(s) 3.0.0
OreEarn 2.0.0 by MomentariyModder for API(s) 3.0.0
Perks 4.4 by FlxiBoy for API(s) 3.22.0, 3.22.1
PiggyCrates 2.1.0 by DaPigGuy for API(s) 3.22.1
PlayerSelectors 1.0.8 by Ad5001 for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
RandomMOTD 1.0.0 by  for API(s) 3.0.0
RedstoneCircuit 1.0.1 by tedo0627 for API(s) 3.6.0
Reports 1.1.0 by Didah (@Diduhless) for API(s) 3.0.0
Rewards 4.0 by Wertzui123 for API(s) 3.0.0
Scoreboard 1.1.2 by Ayzrix for API(s) 3.0.0
SimpleHeal 1.0.0 by Electro for API(s) 3.0.0
SimpleLay 2.1.7 by brokiem for API(s) 3.16.0
SimpleNPC 2.1.6 by brokiem for API(s) 3.20.0
Sponges 1.1.0 by  for API(s) 3.0.0
TotemJoin 1.0.0 by Shelly7w7 for API(s) 3.0.0
TreeCapitator 1.0.8 by  for API(s) 3.0.0
Trident 1.0.0 by brokiem for API(s) 3.15.0
VanillaElytra 1.0.2 by JavierLeon9966 for API(s) 3.9.0
VanillaInventory 1.1.2 by korado531m7 for API(s) 3.19.0
VanillaX 2.2.0 by CLADevs for API(s) 3.19.0
VanishV2 2.3 by superbobby for API(s) 3.0.0
WorldGuard 1.1.95 by MihaiChirculete for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
yAnimals 1.1.0 by YarkaDev for API(s) 3.9.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNXQtz20aS/itzdOoiXREUAb6Z0p5lPWwlksWT6NjZxZVrAAxIhCAGwUMSncp/v+6ZATCAZIuS
ma3z1kbEAOjpr7unXwCHf7Z8nqxp9vmWJWnAo9a0325lwZq1puawZ04mE6s/6pjj0WgyabfyWJ3q
DIZWtzseD0Yja9QddMftFksSnrSmf7ayTQyXtE4/H19dzs4vTj+fXl9fXbfarTVLU7rAcyfMDWlC
M5iQcJ8cXxydsNvUtn+lURCG9JNtsygLsoDBWEzTNLhltj0LFqc4uplOeXQeZSyhbrb3zXvzLAjh
j7ytuOWapXmYkR8S8Xd/Sm554JF1nmbEYcTl6xgYc0JG7oJsSWLurli2DiKmCG9s+yK4DaJFjQ39
sllINywhP8Tib7tGIsjY2rbP4b/kB/xcPwuKWAIS5mY86ZEf3DBwVzOeAo8O5yGI0A9ClF8c5osg
Sg8KzJ14SZODNHEPlDjKMweFMA6UHA9KMQK5EGZtTYeDv9qK5OcguuXhLVvDbTCPFyTAS6s4CyMF
XRhzucdQ34MhjBP4F+cOMEz8PHKFZhcs+xSfJDw+WvM8yvYARhBlf8Ktg5G6Bf8lLMuTiPyQLYPU
+AfcdEHT7F2QvdlIQe7tk/8m6+xzQiNvz2z39smUdH9CKmNF5S88mMAB/B12v8JNSm/Z+zfzPaVw
ZGNoamyo+e8SUMsN9byQ7e3jLENLuyimCUhmOi2JiSt6Gh/DvuJj8BU+NKPZwi4Fm0OdTWlV5LC4
UIiskJRgZ/QQFY/e5FnGoxnckzJvL2J3pJhXnpGz75VGq1NHc93bbxdzi7ETmtEZ6JYl2eaSRrCu
YXpx5iZLYHXspSz0p9OTo/nR5/P389Pro+P5+a+nn+dHb/f3JZ+6+oZKfaPuV8V2yfOUvePgqPbq
K0wT1egRjYIJ09DNQ5oxCVUDqQE6j25BtTzZKBgI+jx6h0Yn+R1ZGr+jnuK3/1V+b0KeHS9ptGB7
TY8g1z8PveIj6ENHMdBQBP4eXil5Al7IfxweihvKkf0/W7CAM9AlrMd//W+7tWARaDbExRlR9Net
ozCjuOAdmrLK1bd6HcvqmDieB6HXmnbbrSD97LHb1jRLcgbrPuEZd8H1TPt98PGLAL3CkLpDszth
fTamvZ41pHTAGB33xqOJOTKdnkkd6oz6A6Cbq/kvgii/J5PeyOr26ciw8D/9LvMN6vrUmJi+w9hg
5HfHLul3zEmna5gjg669YZ+8MsnN5YycMCegkTxrTvpGj+xZXcs0uiPDHO+T+/HwMyw94HgZw3yj
Tr9jIbAvLPIE0H6nK89+5mnBEAyIg1AdoO/nKUs+h4GT0AS8JoqQeksQQcIOfk95ZMA1yjmaHbNj
vfZdyx8NJ6OJ36X9Ph34A8e1qOUMu12vOxpaPuuy0ZiNgLwHTgOdGF8fgEWGDnVXxi0NA49mGDlB
WKuI30Wv1V9kt4wNB04Q0WQjAhpc2oW5zd7rLgW59cZen1njoTm0TN8aWu5oQi3a84aTiTemwJrf
r5N6dHKz0+30Xg/7o/GoD/cMh45L6YgNIMZbfYuNB67Vc60BG7uDAbUaBEOILSGnHksUb9bryWgw
mljjvtUfDqzepOeYI7CWEYhl1DPNHtB2JxPTdOqUQr4QFMAqX497XQckarn+ZMj8UbcHMyPgYb/X
tXwL/tMzXdqfPKBgxNkyYdQrBNV7zfqjEXP9IXMts+97Xr9vDhg1PdqDg4k36jk+SIvROimMxoqb
4WuYdDBynbFrgngn48FkOBo5/cmQjsZjz5lYlu8NXN/t1UlETlbgGb+e+GMLGPZGPujE9SZ0MByy
ft8Z9ty+b47paDgYUTZuCLf6aKzRtGF1Gqj8zxTX9OtnLEaNaEJXYONSPsCb+Xriuqw/GDtjx/dY
j/U933NA5u5wMPHdkTPymTV0Bm7DktKI8y9MiXnwetR1BmwEq5x2h+PR2PN6lkl7JqBmzmjoQc44
GfuW6zWIxKGgACv29dDpjp2R64/dPvUpAOhN3AkFGI5vOv3ueNAzPWZC3P6rTFnEGj3ygNQ84WH4
q6W7PX243aocn9mRfo/m2ZInQOJfres8XQah2QOzbYEPpXGAoz1YFl08ZhGFnNArHKPHYvAsqfS3
KfezE31gTUWypJG0bZ0X277EKyABg0UDF86ubuYfr64vTmDojjkppCAYXgDjkXdLI5edMLDFtIZM
H69DG9SBnSbB6tM3Ifk0TLfFJKghGm3+Z8PxfgmyR9DIYR3MoNMTfluDE+YutcYxy75PSy3Igxeb
Y8j6+fo0ciFOw9QVTJ2j7eAtsyxOpwcHECOXudOBOHFQsnpQA6jJATKoNX9EEHK8rtZuUxJvWDSD
JfCdqm2dujzi683R7BzIn0E1iJ8qScAslyw6TUudS+a2E8rtSgjCYREuVoEcct43PNMxq5EG2hrW
XVmvmusZBgs3zKH2cvh9g+Vi9AklXQRZFrKjhNLjHKjuyLNoDDwDS+Jei/RjPtOxaKN1LGbDRe5K
CTRxQ7bATCjhgW3DYZLFz4CRY1iu+MfDJ5RwwqIgJb+Em3wDuW0TR7vV/z6jAi+4CKF8V6w8ieAN
jTDt10AUIzoOC3xfr2FMJ7tz5EDLttW8L/ZwQMS4PJ6dHhQAEB3zMF0GL5Fh80ADWT+hY4X8odsE
C+mXCzXNCpJKHbNlvnzZVCQBeo2bF0ugInnQwIeiCOmXIPqZ4+SVGKrB5nprRO4gOAvpOggivGVn
vqNOFQRR8qN/3sqOQwifLNnc0HRJawj18ebabORd9Yt3Zd01qlK523uYNwm95cchrWmtHGvkkXU0
59kX79bBa2tQzP6z85MbtKV3uaeF4oo4aKrg5zmw4AqXolxqwKrRb+eRtzy8AR53ZYfaxAhH50JB
uZkfXc8/zB5dgnd3dx0GHCH1TrYS+LCJwRKMi3pyWRtuFgFdw2EZbSjx+Atzl7NLbKTCiV+D+2B1
/M+dmaaL1OO1J7rWjmQuQ+ZACnVWn+uLNL4PaqRAOMdvjHeyJi4FUw7pQnmQb38E7r7kgWmhez6N
WDoYmFhza+M7MoiKom0fvxGsbW/cx0uWZjdLHusAy7F6XO03MV5CHQpe3Afr+3n2/nma1vPnb4Ar
eQFsGlvPVXHMF3Bk8CReiqbrQUUMhRAymshmoy4GbfSJRCmhHo+8R3KkF6q0oAegKyZqBy+QQckk
Ikat6VjFcT21eBByLunvPPlIfT9k6bBe7ZtmZ/hSsGLuZ1hswtPU4Xc17tVQU00NB0XD2yDq9szJ
zpxSSRGUo5ioPl3I1t42mEQ9fRakyyBa6MBq4w+MUDjhOsTf6PtdGSGQsu1q7m8ElwoCrqgP5w8Q
qGEdANYOjUh5Q8NsMwvuWQiu+Mvf4k7qU4CqNPZuLdve1r3AykqRVIykOguKEgCKzRhaDjUy1n7T
Mmeir4f+lMwZXdfXVu/lOiwYsG2NlS3SBM1tVKwdlDQQ7QYwBu7ZXIdbjjVNdWCA42lgvlrkX8Ab
f1jnWZjvymhrRAF1wdH2/uWUpptLDgtXPGfX0DVOPBEStu2LPsfb1BqjdXaeh++axTRIsPJMGwD1
M80yq4HwLfc+Mub9k/K/ZalW5CVWjbNngK2m0nDqnTu9aTpqLkseMQf+vyvjVORsm0kOgCZg07l5
GtB9ltC3FzoaNVLXVr8O5IwGC5bc/HazM1ssKQICyUH5YRscZ+FmdqqhkMf1jHrcbG0cvZ2/O7p+
v9PO7SxP2IwlwtzxLY10KZ553ATrOGQXdKM3t+X0EBSR2e2NsGgOa2jVSF1nD2qI3/nvnI3wX72V
8x1qq0gCDMlF+WErLEkgaVZY1Mi/p+v+rUa74uSlLXZwOGv1bo6CVow8Ae1X+uVLUNcQPiZ7oZMQ
1Gxbzb29lUHhF2bLOdXzx2qsXsk9yIxvliwMN6O70c78Q1pQtO2Si+3BnC8ibAk2S7La8BPh6e9+
MKnz8gxg0S3UO+nyLNAfjOij3y7Cvq87prV08z+AK9sOolsXZ/aDe9vevmABhm8YqyPAgaecQAjJ
5DueBF94lO6waalRBcUIVp6FBt9ZOtHRyIEn0LyjUcTS+ZKd7K7y12nKFx7PT7a3rl82C7bCNnSt
BtNHG63KZokvLk3oH2u62pl6NJq2rfHyTFjXNFqlD3EVw0+E0n8PMMXMc5HlIXsMmRp+0Ht9GbJn
GOEjwCQv2wO7pIvAnbOQzXiS1d6pa55pKq7f7NkEebjZFTJJzbbXz3lyirXvNUuZ3jCrxuo56wPD
O6PhaqtHp1s82hA56UeaYIsCSyJMhvS3L8B4V0GyAh+IbwglyB6g1DjdHupRnvHH4IrxJ/zizzza
vIX70t/mu6t9daIaKOSncbgVzjzMgo88wbc3K5DVYNNNbvWko93y802epfkqgM8rsLVglf49zz/W
yOodsgrgdba/59mHRghE9J7dQV6da/IpRp5oE8NlM/ne+66eeH3PQ8mrhJ3SRO/jFCPNlLj5cIPj
C6s0CbDL4jWepu+sH+kuPX73/tfzk/Mj21acbQ8OCteVXovJ43qbtdkJCO+DN3zTLFcQ/CN1y0tx
+TCLw8HRCo6eAUi8XZbQjNVgaaN1rT3I+k8oXPw233xnOfbEa27FLOLbNQVrtYMXLMWC6IFG5kAI
RdQYNxAy8QsuNcE0zjQd87jRP/EG3a65M48kyRVf3Cm5eIa284QdL6keV8uhRjurYza8zLB/dtbt
PnNRVs2eRzoLVHwDIZ0lGEE+sduA5+ns1CjGNfV/lpMDcsVt9ekFehdMqW8mlWT+0jtTdfEU3aq6
fHqPiYf8JwE4v4NeziM/iPDbSzvyyTURCI60jzsQgqQDUpAv2V1ezfX6TBv8di6yI7R6L7qae3tD
v2YeeJKIHQeJmwe6vTfPPPHWT8Y83h1a9TbN8DseNKvpm1C+9pTvmsWQtac1AHLkiW7MSeDRJdl7
DX/zJdQS6f7O3JBXkLTtRDIDSiq5erYXLqhJuHc08epw5UjjUeZX3/34G97xUCy8+NW7itaBIiWi
jHhxyuFwrMHVBpsKbqTER5svSXD/ve1dEfpKj9tuOGVZAKmxVvvrjfyb1UY0hfAjw1ZK4GJv6g1+
nxK/zzVLglROcBXhlznn+PXcduuYrx2aXfDFQvSNzoLFsjq63MxC8br1MQcndbNJ8b1NLRgK/LZd
SWx79yBxYZtUF301+ES9dYqBN+G7sjVFDqCUHDwXCj43aSK5EN+kqydvozoQJ+GrgDWefg+/wzUo
gradChYgTylQSW6eu3QUvYOSxkGF+f3s+AFmHGtiHj6N2foO7VWQo9gt0Eo+vg8t0JBoYx4taul5
MfLtELArd38e3W4GA0AmZ93eNOccVmzjpeJq7Ik1tt0DkmfoSXs+UjLxnJ71PGHsGBjJ5BcRK0S1
8W8XBLtSSeOlixoLjcPtoAWe+K6oBkqOPKGkR/3HYAdrSc0PKe5lxcqTONSX/k/DTZbo73nXx594
Z+1nehuw5ILxaDIZDmvQJs/uIJ4FCbvjyUqLW3X65X4QkrnG4TNAl18Lf4i7OvVESrHi+MrioGeu
66vOnLxcpRrNElzJ0Pa+pNzP4QG6Tw2H/6Bfr7aa2BmiR3by0FjZCol456GORL0GUftaTR1Hmscs
cbjjbHb3zLgkKTEgE9WnbdCI7uXbvJ7EaoNNi5sMmm80L2lwvMRiLGRPfO9si3S2Wd1VUBsT2XbF
pP75BVG7QflAIwYCwn0soiwA1mvfZqsNf/sbvzuKf/qMtt2Y/0k9b46iYE1r71qWQ09Uor/RZEWb
T2wn32G1CYS8DRK1bSpZsO2Klyeg4PexaQIIMibZ62gvXBqXM7FFDdxjGBE37oIv0iYMwwtSZNWg
USpePUlZAqg7sdxaRGzB0Ho1K4/IMY/8YEFwIxw7evWReeSGxcQcEHMytaxpd0A+zI8Jbg1hR2ue
eYdnELXJMU3hcknbwIr60BqMx3DJ3RIAGGGQZodwRKMIKiuXGWpfEOouAyZ3w0kPeQQUYnoXGbH8
hhdo5tAcwjT0Xt2QHg66XTtagBjwnZdD+OzzBOiVI9z37QgkIb4pJo/i21jQ9gLfD8DWs81hD2iI
PTzAmRspy7IgWqSHdpRAndjR2Q+Bu9BAwzmUD1HUSMqYd1gc4IZMhyenZ0cfLuZ2JE3D+CNnyeYQ
7bwcQuqCEzkNTVOg6R3+l/gHwskzbuDGN+IaCLZ3qLwMvxJ8OLaje4ffG2ieElVIo0VOF+wwydNS
8kF8iM9Z4H92JBiogaltC9DZrHFbgFcEIxlxhdZztWUUKp+AYEnNwsAcyHzJUkYKiRGaMJItGQHP
lcIHmhEXVSw2egoiN8w9sB8g/8DokNYNXzPcnSp7SDOlPmsTDmeSFEkSJ2F0RTY8TxQtEvgEFB74
gZgBtI07KYUbJPye3ZXkDjzmU9B5Su549GNGaBwzmhCU9RrA4lYdG+QQt7KRuO+WLCJ5vIDwDwQ6
NlqlIja1I0JefVwyZIxkHGaJPAIkSCr25AEZJLDOcCccT54WrIYcpgGo8IllQl6eaDQQSIW9UEhw
jZSlKReKnRLhW/BEuswzj8PCUDt8TYndupG03ZCnzLNbgrOjMOR3BBcbMEPU9g3kNqDkf9AY8Bph
FYY6NSXSPuHWU2Gi6h4CfBFcQAQ0BkJBas6GKFHi9cqiy9Mas68+QkoBFgFypZ5H5DZHqRQrCHxF
1oymeSIWPQGhOwyZBuGwP3IaotgWAaRZ5JaGOSN7alLwOPtIXc4Ia0n07QwQO3ZdpnBazP0+Xzsg
FbCqo3QTuXOargjmsWBHHXHBB5CWMO0CKV62TDj4JdAeXJ62iVjpRDkIWA9tsWkZ7uyEiwNlA44Z
x9Z5BBaEl0jiN0K9gAmsLOH34NkzBmIASMJyo5I5lK1i6NxHW8Vr0CbbJMh+BPFlibjNY+gHhck0
biZ7gCGHdWMJsQgYhkI6FaSatkqFcSR5FKE6PfRcPBZKEN+RSzsEYp36TNbY0SLiha+2vviU4aBE
kiSPMzkqBYaCWQNvCpdQLixKsZ+PJxcEFVvB5enjHKCNoM1xEDRYV0czNNyURV5U2CyEBfD4yUau
ybchd8B4MPISOQ7LYB1kuLTXbEGdTQYCJzdS0l0hWxkYxe1zVNpdIAQvDArW7J0hCRU2lgqAPhRG
8IEwrASQjI/hT00pbRyUleMqJQsOesL9tIRR4EQLwaYhWJuSLqKA2YUHllvq/L9HgKnMt/jH0Pt9
/EMeHAsWlPcsWVLkUgLeA4MnuL2CIZy14MrsWn3FmPABH8WiUPylP+6AQ7EsBEvoMIibJ7hpHSx0
ds/cXPheLlmWCxJjVXk1u3chd0grRNJvXc1Pp2T+7vyGXJxfns/J0Wx2cX56Q2an1wTSwV9Or9sE
LiLzK7jqlHx8d3VxSmbXV8enNzedpgeoycMaDJU4ZiwJuIjH6IdTBOgumfDIQhqlrzVB9pAReMK1
iEsMfMgsvawgBVki4AT/DNaEeL9mbNLIIAnE+BfhZWoyQVkSAc9b+fFiccMcVxhCMMyLGzoPr0Zb
UIk4qC1mLmYDUrLIrtSrvLfEAObF4rSC2usqrOn+4ywp5D2FfEETB1aG4fIwlCmqcECPS1csNWRH
3UXUXeC61zTKRe6hcwJ5WQ42uN8uQkLTCAszlNHV94GWxLuulmCHXEmXLw0ekgeeh17JSwAx5C4i
Ff+pJBwL9gHosNtVWGG2M+EsHsRIYTqSQonNT/i6iLXybnWFoZumrmFEozT5wDbIIyZVs46bIl9E
leGuT2iGypC9fB3L5EpmcESdMPBEoa8TvEjdIHgXbBYI4AiiPCx2+oiAIWZD3IMZbsHI0jRnqdzL
NGWLItlEp4WzVVy1C0XKFEHllB3JDV76VTlh/eMu82iVFrwf0xhHg3W+hhAL0TUhRamAiiRqD0vB
RSVXXC9KlGLFPLQxyLVjxZGY0MAkOIeY2y81dsLlqaZNyz0ZC/ry4mIJSVrqQh2ZSBwMF8pAVmI7
AVZEqgLZI0oPuJP5haQS414gWGfgPRJhhQ5uU/JUVa+aGS+ukl0UIH5BuqD7bVLfskM7iliGCpuq
EAGZ2ZKHMsN0aOYuRSIuWIakCUxIBRnh22Tho87K0KI2yJW7iFY5pdJScQrdarLJkHibGKamQKE8
MbGRFcyoECC8dpXGitIVM0hPIsdSRuT5eDMMKrY65B2kgmI/VMztyPHsQ5vgU2+4MPLuAg/MXuQK
0nuW9A1Bf0qGRdZdJeSpkI52bYcceeColjT0D6CSlFWChw/h1FQwKcH2CBqYthCrsKcR0yuR03v0
auLtvLBDkIkPs2hW5NpV/YelBDKFz7jxxjyOYkMdN4qbS7Xq0uALK/WJWXmhRmxPFSkTZO3SPLTQ
2p9Y8qb9Dpmpe0KaLMQNVBWiyhbEjH5CFwgBdAJiS+NQZCxYXa6BeVzsNEE9HYcBtlFEuZxALcXS
jFzOPwhOU4CEsJ08I1ieC1VW08naolP4mnWWG3jXVHCLVu4xJ19Mi3rlH8TEOkWla0tYquI8UdVp
KutptOQo5TJwKWswkZh0TpLa8ZJD/YoWWJQprChEhQfzaEZxZ+HCU2J7pGge4TmtggXGRFdRJiyq
HfE7DyJZC4v20Y/kk8Pv0eoTcn5C9j59OD/ZJ7jF0BJ4gOvvwN2DJYlXusAwsHxJoHbpVBkgWAIX
lwhhR2Dpn95cFPRVaaON/CgmwwaSCJqQfWCNK8KwwMaL5ogKIbUuj5gWzgX+xrjPA69CSyFNAefG
aFa4TYAve5FFFSAKSMUomA0knSIji7gbBjER94LVXNINWAwWkmt+W9TkGNFUGBCu2CjOySm1Gqzo
hun9kblocEhzl5ufS12Ia5Vt56lqtLiwkDPp6tQ9hrxnSmLIkW6DEKeRbly5KDULxiHc/LeoEyK8
LWyGw3ZxVa2f9mhPSipZ7qUt6mwRcuWCRlEqFWN8RQ8luhFghvhZBEi4+VqES+1mATxisvp1mCTm
MB/Xn+h1igi3LOxdmLhogdYCr4SPE5XwwQ8R2mQVsLgichAGMe0xLruPs0kToAT2USw7YLa4Gf+W
3PTEWsbegJHHHr53qvlGF2OqmEj0e/WleSImc/BNm1Q4IJQnS1DTRO7YSxQ6onopRQAX99SgAz2D
WOQVWUAZllbiqfo1pYQ6D0WkXNMdDUSdBm4Sihipm5jHYhNrYYzqACOZuEY5xJ5whyLBN2LlxDCW
oF+CYKdSZ9HJlR2qqQri2FATZaN680z2oKS+gJGq1aEtcrR3A3eBbwyVy60+HC8h2/S5phFYZYZ8
8FNeueSoGcFKJ16v407ABcfgyDZrLHtggWTYQHTTinWs5dR5Up0XEIQTo4tFAgW07JWpxppsIOCm
2asmPsEfrOCrk6spyMNQLl9GPnQKd0zm1pTgPuo4YyoYrwCIsY7WzYZAW0pemqZUzgOhgkLleWVM
EONx02kRqfQUUYxzXXSQdUdoJ1rjqg3+MV7SNsH9VUR4zsosDFyvzxLItA30QBGGP3m2iFYyVtBa
I0w9kNLCaw4ZJ0Ry4cUKZ6EICs3L88UcDzQtseqqzoJ15atV/EWieD2uBHTNqFl0mDih6PCpm4pu
bqeaQJ3RZyik+e0Ir9y21K5cFVrnRNEA8pmSZ9EjWapB4TGwyFF5s/IY2HGG0sQTiWPgl4Sg+gAg
8vECeqCicSB9HNBTLrKIbDQMaKqqEkgkKb7ZpI4w5QEela6mhdLkObBb7GBNyb9ErgLxsy1aWv+L
REXBUYVJ/bGHgIF5I742IpsGxRMq0Q14LGKJgC4idCryY1Fs4ndzgFcVbnX25byCB/mR4GMsjAoy
elUzTsnZxdF8av00ag8m92a7d99rWz+ZP3mYD4l1vpclDA7AuR6Ou9IVy6P+YF8mefIJg16ryxWO
sQVkrFppIvUQvTDQmrvBBym5m+VJ4ZSLAiUpn00IjwN0IFS54tlPWgjMKJ5rgC3IbPbVmXA1Yipx
fY1ILjIF9cMc2oghUkst5+OxKG/ZPTi+VNV27kq8EVv+nkkAeflG5nDiOsQLrEDlIcOIXDMSpaAP
yUhS+upWu8XuMxal4nXW6Z+tY8gQ9H32cRXrx2Hg3IsHeOUIGEWUprWh2K0TSf8AJlmvtn+/3Ka8
PHZctSt7OYLPriKPJrWxZBPj1/5a3U5PvIzjqh+lqa7IkxorEOLx3ZBut2ea1kT+0orYJ7G6xM9q
vyyw8GpH69rJJcSvGjJI6zzxMkc1hj8nUBMZLgjPKfaLxx/MceRzO/2qm9lFXYRRVgMyO7nSD9cb
EKr4CQT1iVS3evyzlHjt/mVdlFUM+yxSFP0XCMQvKvAUdwDQbqg238cdPkzcqK3dgkolF15oId9p
Ke+/Zr5qz9TktVzzmkDlq5ufLmvgU8Fb+gBvoI8EC/nTCYoffPkn4ysWQb5UA9owVzhEGA+uEb8P
UxvcUHGnpZT2JYjl+xoD8YYsSlkwVd3y11//B0mUqbc=
===END CRASH DUMP===

**Comment by MrNinja008** [comment]
Use pocketmine :/ this plugin is meant to work with pmmp not with spoons example altay. Ig

**Comment by xXNiceYT** [comment]
Use pmmp not altay ^^
