### ISSUE TITLE
Name Tag 

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#119]
Please fix removeentities can’t remove mobs with NameTag

**Comment by xXNiceYT** [comment]
what do you mean by removeentities cant remove mob?

**Comment by SPMP2** [comment]
With nametag normally the mobs don't despawn but with clearlag / command removeentities the mobs despawn...

**Comment by xXNiceYT** [comment]
cant stop a plugin from despawning an entity sorry

**Comment by xXNiceYT** [comment]
thats up to plugin to decide

**Comment by SPMP2** [comment]
Ok no problem !
