### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Glyphs31** [CLADevs/VanillaX#12]
Are the features in this plugin available in the Redstone system? If not, please add it with other features such as end and nether.
In poggit release there are several functional plugins such as Sponges, Firework, PM-Beacons, if I delete these plugins, will this plugin already have features of that plugin?
if you add some features like TeaSpoon or TableSpoon maybe, this plugin is really cool.

**Comment by xXNiceYT** [comment]
Most of features aren’t added just really busy with school but yes those will be possible in the feature.
