### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#120]
Hey i have Bug to report !

- 1 (for me the + important)
ILLEGAL STACK
Item like ShulkerBox, Enchanted book,
If you enchanted with enchanted book stacked, enchanted book isn’t consumed and we can enchanted to infinity

To reproduce this bug: (drop several item on ground / shop several item with trading plugin)

2 - Enchanting Table bug if you enchanted item with 30 lvl, this displays that the 3 are consumed, on the screen you therefore have 27 lvl, but if you gained xp for past lvl 28, your xp is updated to 31 lvl, so the 3 levels are displayed missing, but in reality they do not come off when you enchanted, example, if you are lvl 36 you enchanted an object (enchantment for lvl 30), you will have displayed on the screen that you now have 33 lvl but if you went to lvl 34, your lvl is updated and you pass lvl 37, so the 3 lvl of the lvl 30 enchantment are not consumed

To reproduce this bug: take bottle of xp (enchanted bottle) pass lvl 30, enchant an item with 30lvl, (this display lvl 27) take again bottle xp, and pass lvl 28, you can see, you are now lvl 31 (the 3 lvl isn’t remove to real is just dummy remove 

3 - Frost Walk enchant, you must jump if you want ice place under you feet, if you go normally in water (no jump, ice dont place and you swim in water) 

To reproduce this bug: just enchant with frost walk enchant and try to walk on water, without jumping 

sorry for my english i’m french i am using an translator to report this bugs 

If you don’t understand i can make a short ytb video to show you !

**Comment by xXNiceYT** [comment]
It would be helpful for second bug 'Enchanting Table' to have an video

**Comment by SPMP2** [comment]
Ok i will make a short video in few minutes, can you fix illegal stack? Please bro? (Bug 1 in my comment)

I have modify your plugin and remove anvil and enchant in vanillaX and i am using VanillaInventory (for anvil & enchant) to don't have conflict with my TradeNPC plugin so i will download the orignal VanillaX plugin to show you the enchanting table bug

**Comment by xXNiceYT** [comment]
okay thank you alot

**Comment by SPMP2** [comment]
No problemo, this is the video

https://youtu.be/w9SzQZXco_Y

**Comment by SPMP2** [comment]
Will you fix illegal stack of shulker box / enchanted book ? Please please

**Comment by xXNiceYT** [comment]
can't do it right now man sorry but ill be doing it soon

**Comment by SPMP2** [comment]
Okok niceee thank you very mutch !

**Comment by xXNiceYT** [comment]
Fixed the small bug but enchanting table one is pretty big can't do huge tests rn

**Comment by SPMP2** [comment]
Nice thank you so mutch bro ! Best dev 🙏
