### ISSUE TITLE
PM4

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#121]
1. Eror In Console and Crashdump : 
     Error: Too few arguments to function pocketmine\crafting\CraftingManager::getFurnaceRecipeManager(), 0 passed in /root/pm4/plugins/VanillaX-4.0/src/CLADevs/VanillaX/entities/utils/ItemHelper.php on line 88 and exactly 1 expected
File: pmsrc/src/crafting/CraftingManager
Line: 139
Type: ArgumentCountError

2. Fireworks not working in pm4

**Comment by xXNiceYT** [comment]
fixed both
