### ISSUE TITLE
BUG tap to armor 2 CHESTPLATES

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#123]
If you use elytra and you tap to armor with chestplate, the chestplate go on place of the helmet and if you replace elytra by chestplate you can have 2 chestplate

To reproduce this bug just take an elytra, take an chestplate tap to armor, the chestplate will take place of the helmet, (you can use elytra and chestplate) and take chestplate, replace elytra by this helmet.... you got 2 chestplates

**Comment by xXNiceYT** [comment]
this should be fixed in 4.0 sorry but 3.0 has alot bugs that i havent fixed which 4.0 has

**Comment by SPMP2** [comment]
Ok no problem bro, can you please tell me where is "tap to armor" on vanillaX files ? Because i will try to remove that feature and use tap to armor plugin because if i am using tap to armor plugin, with the tap to armor vanillaX this make conflict and we can duplicate armor.... i am searching in vanillaX files but i don't found it

**Comment by xXNiceYT** [comment]
yeah its this https://github.com/CLADevs/VanillaX/blob/master/src/CLADevs/VanillaX/listeners/types/PlayerListener.php#L72&#L68

**Comment by SPMP2** [comment]
Thank you very mutch !!! 🙏

**Comment by xXNiceYT** [comment]
ty
