### ISSUE TITLE
Hoppers Issues and Feature Request

### ISSUE THREAD

**Issue by CallMeApache** [CLADevs/VanillaX#125]
Issues: 
  - Hoppers Pickup Items Through the Ground.
  - Hoppers Can and Will Pickup Items Instantly Even 300 Blocks in the Air.
 
Feature Request:
  - Hoppers Grab Items From Containers and Move Through Hoppers

**Comment by xXNiceYT** [comment]
The issues you’ve told me could not be reproduced, tried it but non of them worked. And thanks for the suggestion
