### ISSUE TITLE
Horrible

### ISSUE THREAD

**Issue by Octqne** [CLADevs/VanillaX#127]
This dosent work i tried it 1min ago it has 12 errors

**Comment by CodsXBlastin** [comment]
shut

**Comment by xXNiceYT** [comment]
ur just blind it has no issues it’s prob ur core that has issues

**Comment by Octqne** [comment]
> ur just blind it has no issues it’s prob ur core that has issues

False it said your plugin has a error which is onDisable is going null wtf

**Comment by xXNiceYT** [comment]
It went null just like ur dad

**Comment by MonoAdrian23** [comment]
Pocketmine Devs are unfriendly. Pocketmine is a shit of Software and for
kiddies!

xXNiceYT ***@***.***> schrieb am Mo., 8. Nov. 2021, 12:17:

**Comment by MonoAdrian23** [comment]
U should use Powernukkit! Its much more better as Stupid Shit of Pocketmine

**Comment by xXNiceYT** [comment]
Thank you @MonoAdrian23, so inspirational I will be using power nukkit
