### ISSUE TITLE
Bug Enchant with BOOK

### ISSUE THREAD

**Issue by xodamcm** [CLADevs/VanillaX#128]
I have found an little bug, when you click with book to an item, this item will be enchant!! Little video to understand better

(https://youtu.be/TQSFEVU6co0)

**Comment by ItsRealNise** [comment]
You using piggycustomenchant disable it in plugin_data > piggycustomenchant

**Comment by xodamcm** [comment]
Ooooh ok!!!! Thank you very mutch !!🙏
