### ISSUE TITLE
Spawn Egg

### ISSUE THREAD

**Issue by xodamcm** [CLADevs/VanillaX#131]
When player click (pickup) on mob this get spawnegg

**Comment by xXNiceYT** [comment]
Thanks I’ll check it once I can

**Comment by xodamcm** [comment]
You’re welcome ! (On packet listener)
Remove or put if player is op / player is on creative


case ProtocolInfo::ACTOR_PICK_REQUEST_PACKET:
   if($packet instanceof ActorPickRequestPacket) $this->handleActorPickRequest($player, $packet)

    private function handleActorPickRequest(Player $player, ActorPickRequestPacket $packet): void{
        $entity = $player->getLevel()->getEntity($packet->entityUniqueId);

        if($entity instanceof Entity && !$entity instanceof Human){
            $result = ItemFactory::get(ItemIds::SPAWN_EGG, $entity::NETWORK_ID);
            $ev = new PlayerBlockPickEvent($player, BlockFactory::get(BlockIds::AIR), $result);
            $ev->call();

            if(!$ev->isCancelled()){
                $player->getInventory()->setItemInHand($ev->getResultItem());
            }
        }
    }
