### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xodamcm** [CLADevs/VanillaX#133]
How to use on Pocketmine 4.0 please?

**Comment by xXNiceYT** [comment]
Same way you use 3.0

**Comment by xXNiceYT** [comment]
1. Get phar from here https://github.com/pmmp/PocketMine-MP/releases
2. https://dev.azure.com/pocketmine/PHP-Builds/_build/results?buildId=479&view=artifacts&pathAsName=false&type=publishedArtifacts Download bin from here 
Ur done

**Comment by xodamcm** [comment]
We dont need to change APi on plugin.yml?

**Comment by xXNiceYT** [comment]
Plugin had nothing to do with ur question, yes u do need to change api and all api changes happened on 4.0

**Comment by xodamcm** [comment]
For me even if i change api on plugin.yml vanillaX doesn’t work for pm4

**Comment by xXNiceYT** [comment]
VanillaX has a repo that is for 4.0, the  master repo is for 3.0 currently which will be changed to 4.0 soon as I am available
