### ISSUE TITLE
VanillaX doesn't validate InventoryTransactionPacket

### ISSUE THREAD

**Issue by ipad54** [CLADevs/VanillaX#135]
https://youtu.be/sPpmsabqSnc

PM4

**Comment by xXNiceYT** [comment]
Thank you I was looking forward to this. I could not test it myself because I didn’t had any hack clients now it’s confirmed, that fake items works I’ll fix it

**Comment by ipad54** [comment]
You can download Toolbox on your phone

**Comment by xXNiceYT** [comment]
Yeah, but I don’t got any androids. I mostly use my pc for gaming, and downloading those hacks might have virus so I just try not to get them unless it’s horion which I can compile it myself

**Comment by ipad54** [comment]
Try https://github.com/disepi/ambrosial

**Comment by xXNiceYT** [comment]
Thanks, does it have give command which gives fake item? Or duper like how horion had

**Comment by ipad54** [comment]
.give

**Comment by xXNiceYT** [comment]
@ipad54 this might be fixed in 4.0 by dylan i cant do .give and keep item given to me by the hack client

**Comment by ipad54** [comment]
A hacker can send an InventoryTransactionPacket directly to the trading inventory

**Comment by xXNiceYT** [comment]
true ill check on that
