### ISSUE TITLE
Glass bottle -> Water Bottle

### ISSUE THREAD

**Issue by xodamcm** [CLADevs/VanillaX#139]
It’s possible to add this feature ?

**Comment by xXNiceYT** [comment]
What

**Comment by xodamcm** [comment]
When we click on water on pocketmine with glass bottle, this doesn't get water bottle and we can't make potion on brewing stand without this feature ..

**Comment by xXNiceYT** [comment]
Ah will add it

**Comment by xodamcm** [comment]
Nice! Thank's very mutch
