### ISSUE TITLE
bug when launch fireworks

### ISSUE THREAD

**Issue by serezha13** [CLADevs/VanillaX#141]
Error: "Typed property pocketmine\entity\Entity::$gravity must not be accessed before initialization" (EXCEPTION) in "pmsrc/src/entity/Entity" at line 806
Error: "Typed property pocketmine\entity\Entity::$drag must not be accessed before initialization" (EXCEPTION) in "pmsrc/src/entity/Entity" at line 806

**Comment by xXNiceYT** [comment]
Try using latest plugin, it seems to not happen to me. i just got fireworks from creative and tried using it, works fine

**Comment by NopeNotDark** [comment]
doesn’t work in survival

**Comment by xXNiceYT** [comment]
It does work in survival

**Comment by NopeNotDark** [comment]
bs
