### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NopeNotDark** [CLADevs/VanillaX#143]
Error: "Typed property pocketmine\entity\Entity::$gravity must not be accessed before initialization" (EXCEPTION) in "pmsrc/src/entity/Entity" at line 1209
Error: "Typed property pocketmine\entity\Entity::$drag must not be accessed before initialization" (EXCEPTION) in "pmsrc/src/entity/Entity" at line 1209

**Comment by xXNiceYT** [comment]
Not helpful at all 😭
