### ISSUE TITLE
Some bug: When End Crystal on Bedrock explosion

### ISSUE THREAD

**Issue by edwinyoo44** [CLADevs/VanillaX#147]
`2022-02-14 [20:06:27.501] [Server thread/CRITICAL]: TypeError: "pocketmine\world\World::isInWorld(): Argument #1 ($x) must be of type int, float given, called in phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.0.phar/src/world/World.php on line 1811" (EXCEPTION) in "pmsrc/src/world/World" at line 1523
`

`
--- Stack trace ---
  #0 pmsrc/src/world/World(1811): pocketmine\world\World->isInWorld(double -2328.5, integer 68, double -899.5)
  #1 pmsrc/src/player/Player(1655): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3#372387, object CLADevs\VanillaX\items\types\EndCrystalItem#426379, integer 1, object pocketmine\math\Vector3#254640, object pocketmine\player\Player#150939, true)
  #2 pmsrc/src/network/mcpe/handler/InGamePacketHandler(444): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3#372387, integer 1, object pocketmine\math\Vector3#254640)
  #3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(305): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#289132)
  #4 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/InGamePacketHandlerX(223): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#232853)
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(105): CLADevs\VanillaX\network\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#232853)
  #6 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\InGamePacketHandlerX#270607)
  #7 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#232853, string[56] ......$C......@...............iM..r..B..`....>...?.X.?..)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[57] c.aJg.b.9.&...*..|L..8.......2}.....9ulL8..`...C.=C...+F.)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 5, string[66] ..I....j8..L..R.n..Y..`N...v~.1Jn.jY.Y...%...LD..*.z\.S1..h."Z..u.)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32382)
  #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644840387.0347)
  #14 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #16 pmsrc/src/PocketMine(327): pocketmine\server()
  #17 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.0.phar/src/Pock)
--- End of exception information ---
`

**Comment by xXNiceYT** [comment]
How do I reproduce this error?

**Comment by edwinyoo44** [comment]
> How do I reproduce this error?

1. Put the End Crystal on the Bedrock
2. Click it to make it explode

keep repeating these two steps
