### ISSUE TITLE
Undefined constant CLADevs\VanillaX\enchantments\armors\BindingEnchantment::BINDING

### ISSUE THREAD

**Issue by crischutu07** [CLADevs/VanillaX#150]
[Tue_Feb_15-06.30.23-UTC_2022.log](https://github.com/CLADevs/VanillaX/files/8066474/Tue_Feb_15-06.30.23-UTC_2022.log)

api 4 1.18.10

**Comment by xXNiceYT** [comment]
This is old version of vanillax
