### ISSUE TITLE
Major Mob Issue and Suggestion & more

### ISSUE THREAD

**Issue by TheBalkanDev** [CLADevs/VanillaX#16]
Hey,

i LOVE this Plugin and the goal to make PMMP like Vanilla is very very nice.

ISSUE: This Plugin isn‘t compatible with PEX (PureEntitiesX) pls fix.

SUGGESTION: You can add new Blocks very easily for example the Barrel with this API/Plugin 
https://github.com/JavierLeon9966/ExtendedBlocks

NOTICE: Please add the new Blocks

Question: How I can use the Ender Dragon?

**Comment by xXNiceYT** [comment]
Hey, it been while I’ve updated this plugin I am kinda busy with irl works.
But I will add PureEntitiesX support in the future, it can be option inside Config itself such as like
toggle-pex: true or false

The new blocks will also be added shortly, lastly the entities aren’t functional.

**Comment by TheBalkanDev** [comment]
Thanks for answering.

How many months do you think the Plugin has PEX Support and the new Blocks.
Entity functionality it’s very unimportant, I can code an PEX Addon 
 for this.

**Comment by xXNiceYT** [comment]
Not currently sure when I will add them, but yes I know entity functionality is important but it needs to be less laggy than most of entity plugin. So I need to improve it later on

**Comment by TheBalkanDev** [comment]
Okay can I help in some ways?

**Comment by xXNiceYT** [comment]
Thanks you, but you could make a pull request if you want.

**Comment by TheBalkanDev** [comment]
Yes
