### ISSUE TITLE
PLEASE FIX INTERNAL SERVER ERROR IN API 3

### ISSUE THREAD

**Issue by Rishav7778** [CLADevs/VanillaX#161]
[Mon_Mar_14-21.07.25-CDT_2022.log](https://github.com/CLADevs/VanillaX/files/8249598/Mon_Mar_14-21.07.25-CDT_2022.log)

**Comment by xXNiceYT** [comment]
not my fault

**Comment by NopeNotDark** [comment]
Retrace your steps, Tell us what you did. Giving a log file of the crash doesn’t provide us with a brief list.

**Comment by PocketMiner92** [comment]
API 3 is Not longer Supported!
Today it comes the new Minecraft Update and you have Many Problems with youre "Api3" Server!
Because Pocketmine 3 dont get an Update!
You must Change to API 4

**Comment by CodsXBlastin** [comment]
switch to dragonfly
