### ISSUE TITLE
Where is the copper items?

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#164]
![image](https://user-images.githubusercontent.com/85447029/159769376-f616355d-c760-4cc9-b9e5-26b4a1d34cdf.png)
![image](https://user-images.githubusercontent.com/85447029/159769482-3cd05adb-e956-4ba0-bbdb-e269393324c4.png)
In spanish is called "Cobre" but there is no blocks.

VanillaX version: 3.0.0 (latest dev)
PHP: 8.0.16
PMMP Version: 4.2.4
OS: linux
plugins: VanillaX only

**Comment by NopeNotDark** [comment]
try using it in english

**Comment by MrBlasyMSK** [comment]
> try using it in english

Still dont work and all items appearing in the object list are automatically changed to spanish by default.

**Comment by xXNiceYT** [comment]
Weird I’ll check these items
