### ISSUE TITLE
How to download this plugin 

### ISSUE THREAD

**Issue by Zenxq** [CLADevs/VanillaX#165]
How do i download this?

**Comment by CodsXBlastin** [comment]
you dont

**Comment by xXNiceYT** [comment]
1. Get DevTools: https://poggit.pmmp.io/p/DevTools
2. Download VanillaX zip from github: https://codeload.github.com/CLADevs/VanillaX/zip/refs/heads/4.0
3. Extract that VanillaX zip into your server plugins folder
