### ISSUE TITLE
server happened when server restart the item in furnace lose 

### ISSUE THREAD

**Issue by xS91D** [CLADevs/VanillaX#166]
server happened when server restart the item in furnace lose

**Comment by xXNiceYT** [comment]
any error?

**Comment by xS91D** [comment]
Nope but the problemstill happened

**Comment by xXNiceYT** [comment]
How do I recreate this issue in my server?

**Comment by xS91D** [comment]
Just put item in furnace and let furnace work after 1min and restart server.

**Comment by xXNiceYT** [comment]
I put in a beef uncooked and used coal as fuel waited for a min and restarted the item saves for me

**Comment by sdsd20021127** [comment]
https://youtu.be/62l9nIoB-Us
