### ISSUE TITLE
Copper blocks do not appear if the Spyglass plugin is installed

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#167]
#164
Pls reopen that, in the last version the items of copper there arent at the inventory or in the /give command

**Comment by xXNiceYT** [comment]
The creative should have copper with name of cobre in Spanish I checked last time but /give is prob not going to work atm for coppers

**Comment by MrBlasyMSK** [comment]
Still not in creative

**Comment by xXNiceYT** [comment]
did u used the latest plugin? i just double checked copper items are in creative inventory just not /give

**Comment by MrBlasyMSK** [comment]
Yes, I have downloaded the latest version few hours ago and it still does not appear

**Comment by xXNiceYT** [comment]
try installing VanillaX this way, it seems to work fine for me.

Installing VanillaX:
1. Get DevTools: https://poggit.pmmp.io/p/DevTools
2. Download VanillaX zip from github: https://codeload.github.com/CLADevs/VanillaX/zip/refs/heads/4.0
3. Extract that VanillaX zip into your server plugins folder

**Comment by MrBlasyMSK** [comment]
> try installing VanillaX this way, it seems to work fine for me.
> 
> Installing VanillaX:
> 
> 1. Get DevTools: https://poggit.pmmp.io/p/DevTools
> 2. Download VanillaX zip from github: https://codeload.github.com/CLADevs/VanillaX/zip/refs/heads/4.0
> 3. Extract that VanillaX zip into your server plugins folder

I have tested it only with those 2 plugins and it works correctly, I think there is some plugin that is interfering with it, I will try to see which one it is.

**Comment by MrBlasyMSK** [comment]
@xXNiceYT I have found the plugin which makes copper objects not to be displayed

Poggit: https://poggit.pmmp.io/p/spyglass
Github: https://github.com/ItsRealNise/Spyglass/tree/main

**Comment by PocketMiner92** [comment]
Pocketmine is such a useless ....

**Comment by xXNiceYT** [comment]
its up to that creator to make vanillax compatible with spyglass
