### ISSUE TITLE
No thunder or sound of thunder when set to /weather thunder

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#168]
I have been checking for a while that there is no thunder and no sound of thunder.

You can look at this plugin that does add them:
https://github.com/tgwaste/Weather/blob/main/src/tgwaste/Weather/Weather.php

Maybe it's because yours doesn't have this?:

```php
		if (Main::$instance->weather >= Main::LIGHT_THUNDER) {
			$this->playThunder();
			$this->sendLightning();
```
I don't understand programming so I just came to report this.

**Comment by xXNiceYT** [comment]
Thank you alot for reporting :)
