### ISSUE TITLE
bug crash map

### ISSUE THREAD

**Issue by TukangM** [CLADevs/VanillaX#169]
[05:09:56.565] [Server thread/INFO]: [Track] Bapak Gile Gg > /mw tp gacha
[05:10:22.859] [Server thread/INFO]: Preparing world "Sumo - Map"
[05:10:22.863] [Server thread/CRITICAL]: Error: "Call to a member function getValue() on null" (EXCEPTION) in "plugins/VanillaX-4.0/src/CLADevs/VanillaX/world/gamerule/GameRuleManager" at line 140
--- Stack trace ---
  #0 plugins/VanillaX-4.0/src/CLADevs/VanillaX/listeners/types/WorldListener(36): CLADevs\VanillaX\world\gamerule\GameRuleManager->sendChanges(object pocketmine\player\Player#97152, object pocketmine\world\World#131622)
  #1 pmsrc/src/event/RegisteredListener(75): CLADevs\VanillaX\listeners\types\WorldListener->onLevelChange(object pocketmine\event\entity\EntityTeleportEvent#139303)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityTeleportEvent#139303)
  #3 pmsrc/src/entity/Entity(1411): pocketmine\event\Event->call()
  #4 pmsrc/src/player/Player(2368): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#136626, NULL , NULL )
  #5 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/subcommand/TeleportSubCommand(65): pocketmine\player\Player->teleport(object pocketmine\world\Position#136626)
  #6 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/command/MultiWorldCommand(98): czechpmdevs\multiworld\command\subcommand\TeleportSubCommand->execute(object pocketmine\console\ConsoleCommandSender#139419, array[2], string[8] teleport)
  #7 pmsrc/src/command/SimpleCommandMap(220): czechpmdevs\multiworld\command\MultiWorldCommand->execute(object pocketmine\console\ConsoleCommandSender#139419, string[2] mw, array[2])
  #8 plugins/SimpleNPC.phar/src/brokiem/snpc/entity/CustomHuman(129): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#139419, string[26] mw tp pvp "SpringZeus3867")
  #9 plugins/SimpleNPC.phar/src/brokiem/snpc/EventHandler(58): brokiem\snpc\entity\CustomHuman->interact(object pocketmine\player\Player#97152)
  #10 pmsrc/src/event/RegisteredListener(75): brokiem\snpc\EventHandler->onDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#130896)
  #11 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#130896)
  #12 pmsrc/src/entity/Entity(530): pocketmine\event\Event->call()
  #13 pmsrc/src/entity/Living(517): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#130896)
  #14 pmsrc/src/player/Player(1727): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#130896)
  #15 pmsrc/src/network/mcpe/handler/InGamePacketHandler(520): pocketmine\player\Player->attackEntity(object brokiem\snpc\entity\CustomHuman#95477)
  #16 pmsrc/src/network/mcpe/handler/InGamePacketHandler(304): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#131997)
  #17 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/InGamePacketHandlerX(205): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#135576)
  #18 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(105): CLADevs\VanillaX\network\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#135576)
  #19 pmsrc/src/network/mcpe/NetworkSession(397): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\InGamePacketHandlerX#128941)
  #20 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#135576, string[32] .........Z.Cr=.B..kC............)
  #21 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[105] c.abc.b.j.......iw.j.rf....KM.JL+.*.I.L-b`P.c`f`a.b..........V.3..0...b.........)
  #22 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[114] .....Djd.../!*..?...Y.bWg..:.........a..g)../]...x.#D3.Z..l.......).sA.O.8.Q|.f.)
  #23 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#28560)
  #24 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #25 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #26 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1649740222.8367)
  #27 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #28 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #29 pmsrc/src/PocketMine(327): pocketmine\server()
  #30 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[05:10:22.864] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[05:10:22.867] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Tue_Apr_12-05.10.22-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[05:10:22.868] [Server thread/EMERGENCY]: Forcing server shutdown

Is it because of the barrier? because previously put a block barrier on the map

**Comment by TukangM** [comment]
iron block crash server or gamerule overwrite multiworld

**Comment by TukangM** [comment]
[07:11:06.143] [Server thread/INFO]: [Track] Bapak Gile Gg > /st
[07:11:13.417] [Server thread/INFO]: Enabling VanillaX v3.0.0
[07:11:13.586] [Server thread/CRITICAL]: Error: "Call to a member function getValue() on null" (EXCEPTION) in "plugins/VanillaX-4.0/src/CLADevs/VanillaX/world/gamerule/GameRuleManager" at line 166
--- Stack trace ---
  #0 plugins/VanillaX-4.0/src/CLADevs/VanillaX/world/weather/WeatherManager(34): CLADevs\VanillaX\world\gamerule\GameRuleManager->getValue(string[14] doweathercycle, object pocketmine\world\World#154416)
  #1 plugins/VanillaX-4.0/src/CLADevs/VanillaX/world/WorldManager(22): CLADevs\VanillaX\world\weather\WeatherManager->startup()
  #2 plugins/VanillaX-4.0/src/CLADevs/VanillaX/VanillaX(57): CLADevs\VanillaX\world\WorldManager->startup()
  #3 pmsrc/src/plugin/PluginBase(137): CLADevs\VanillaX\VanillaX->onEnable()
  #4 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 plugins/ServerTools.phar/src/matcracker/ServerTools/forms/plugins/manager/PluginEnablerForm(54): pocketmine\plugin\PluginManager->enablePlugin(object CLADevs\VanillaX\VanillaX#25087)
  #6 plugins/ServerTools.phar/src/matcracker/ServerTools/libs/matcracker/FormLib/BaseForm(78): matcracker\ServerTools\forms\plugins\manager\PluginEnablerForm::matcracker\ServerTools\forms\plugins\manager\{closure}(object pocketmine\player\Player#26425, integer 42)
  #7 pmsrc/src/player/Player(1999): matcracker\ServerTools\libs\matcracker\FormLib\BaseForm->handleResponse(object pocketmine\player\Player#26425, integer 42)
  #8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(894): pocketmine\player\Player->onFormSubmit(integer 8, integer 42)
  #9 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(46): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#179915)
  #10 pmsrc/src/network/mcpe/NetworkSession(397): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object CLADevs\VanillaX\network\InGamePacketHandlerX#128802)
  #11 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#179915, string[6] e..42.)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[9] cK.`61...)
  #13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[18] ...._....h.[.%....)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#111139)
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #17 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1649747473.4469)
  #18 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #19 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #20 pmsrc/src/PocketMine(327): pocketmine\server()
  #21 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[07:11:13.586] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[07:11:13.591] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Tue_Apr_12-07.11.13-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[07:11:13.591] [Server thread/EMERGENCY]: Forcing server shutdown

another crash

**Comment by TukangM** [comment]
remove gamerules?. maybe vanillaX overrides the Multiworld code. so when you go to another map it crashes #9

**Comment by xXNiceYT** [comment]
the issue is that ur level.dat file in ur world folder does not have GameRule key set thats why its happening due to prob pmmp not generating it

**Comment by TukangM** [comment]
ok

**Comment by TukangM** [comment]
> the issue is that ur level.dat file in ur world folder does not have GameRule key set thats why its happening due to prob pmmp not generating it

still waiting update

**Comment by xXNiceYT** [comment]
> > the issue is that ur level.dat file in ur world folder does not have GameRule key set thats why its happening due to prob pmmp not generating it
> 
> still waiting update

you can change that yourself, try dropping ur level.dat into this and adding GameRule key http://irath96.github.io/webNBT/

**Comment by TukangM** [comment]
> > > the issue is that ur level.dat file in ur world folder does not have GameRule key set thats why its happening due to prob pmmp not generating it
> > 
> > 
> > still waiting update
> 
> you can change that yourself, try dropping ur level.dat into this and adding GameRule key http://irath96.github.io/webNBT/

what do i have to change?

**Comment by xXNiceYT** [comment]
Add a new GameRule data into your level.dat, pocketmine should of done it automically for you not sure why it did not
