### ISSUE TITLE
Netherite armor cannot be put on item frames

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#170]
I wanted to sell Netherite items in my store but I have seen that Netherite armor pieces can not be colored in item frames because it puts the piece when you right click on it, I should first see if you are looking at an item frame to place it and if there is none then put the piece on your body.

**Comment by TukangM** [comment]
https://poggit.pmmp.io/p/Netherite try this

**Comment by MrBlasyMSK** [comment]
> https://poggit.pmmp.io/p/Netherite try this

Even if I add another Netherite plugin this plugin interferes in that it equips the armor automatically without taking into account if you are looking at an itemframe or not, so the only way to put Netherite objects in item frame is to remove the plugin, but I would not like to do it, that's why I report it.

**Comment by PocketMiner92** [comment]
Another Kiddie Server without Qualitys.
