### ISSUE TITLE
Netherite objects burn

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#171]
Netherite objects should theoretically not burn, but those integrated by VanillaX do.

**Comment by PocketMiner92** [comment]
https://discord.gg/Gh9Jrn62ye

**Comment by MrBlasyMSK** [comment]
> https://discord.gg/Gh9Jrn62ye

https://discord.gg/dPmK9zVBeh

**Comment by ghost** [comment]
Эй Дилан я здесь. Эх Дилан Дилан богом дан дилаааааан

**Comment by TukangM** [comment]
https://poggit.pmmp.io/p/Netherite

> Netherite objects should theoretically not burn, but those integrated by VanillaX do.

https://poggit.pmmp.io/p/Netherite

this plugin not burning netherite
