### ISSUE TITLE
Furnace Experience Bug

### ISSUE THREAD

**Issue by xodamcm** [CLADevs/VanillaX#173]
Hi, in VanillaX pm3, furnace drop experience orb, it is good, almost like vanilla

on VanillaX pm4, you must to break the furnace to earn experience orbs

**Comment by PocketMiner92** [comment]
Pocketmine 3 is Not longer Supported!

**Comment by xodamcm** [comment]
I know, please read the whole message, i say, in pm3 furnace functionality work fine but not in pm4 

Sorry, i have just edited my message because i have right 2x pm3
