### ISSUE TITLE
No lightning or sound of lightning

### ISSUE THREAD

**Issue by MrBlasyMSK** [CLADevs/VanillaX#174]
Theoretically this was corrected in the latest version, but there is still no lightning in /weather thunder and there is no lightning sound either.

**Comment by PocketMiner92** [comment]
This is why all professionell Users use Powernukkit.

**Comment by xXNiceYT** [comment]
> This is why all professionell Users use Powernukkit.

Shut yo goofy ass up 🤣 the issue is likely cause because the chance of lightning happening is very very high same as vanilla. I got life unlike those powernukkit devs
