### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by Wayder228** [CLADevs/VanillaX#175]
How to download the latest version? Google doesn’t have the last one, the last one was in 2021.

**Comment by xXNiceYT** [comment]
1. Get DevTools: https://poggit.pmmp.io/p/DevTools
2. Download VanillaX zip from github: https://codeload.github.com/CLADevs/VanillaX/zip/refs/heads/4.0
3. Extract that VanillaX zip into your server plugins folder

**Comment by Wayder228** [comment]
>
Спасибо
