### ISSUE TITLE
VanillaX Bug

### ISSUE THREAD

**Issue by FunkaDev** [CLADevs/VanillaX#177]
vanillax created an acid bug plugin, when I removed the vanillax plugin. that bug is no longer there. is there any solution?
![IMG-20220430-WA0000](https://user-images.githubusercontent.com/76087633/166122919-1de67b74-29be-4cac-af2f-e55ae6bdd583.jpg)

**Comment by xXNiceYT** [comment]
Nope this is the acid plugin bug

**Comment by FunkaDev** [comment]
but, when i remove vanillax, there is no such bug at all, it's why?

**Comment by FunkaDev** [comment]
> Nope this is the acid plugin bug

but, when i remove vanillax, there is no such bug at all, it's why?
