### ISSUE TITLE
underproduction.

### ISSUE THREAD

**Issue by Wayder228** [CLADevs/VanillaX#178]
The crystal cannot be placed on obsidian, and make it so that the crystal does not explode everything around, because it interferes, or make a switch.

**Comment by xXNiceYT** [comment]
crystal suppose to explode when u tap them

**Comment by Wayder228** [comment]
> кристалл должен взорваться, когда вы нажмете на них

It explodes, but you can't put the Crystal on the obsidian.

**Comment by xXNiceYT** [comment]
That should be fixed on last update :)

**Comment by Wayder228** [comment]
> Это должно быть исправлено в последнем обновлении :)

I'm waiting for an update.

**Comment by xXNiceYT** [comment]
should be updated in the latest update
