### ISSUE TITLE
Bug Fast

### ISSUE THREAD

**Issue by ItsRealNise** [CLADevs/VanillaX#179]
if you activate the beacon effect it will hit everyone on the server

**Comment by xXNiceYT** [comment]
What you saying is that, once beacon is activated it gives everyone effect that aren’t in beacon radius?

**Comment by ItsRealNise** [comment]
yes the effect not in beacon radius but all players in server

**Comment by ItsRealNise** [comment]
and bug using proxy or wdpe rain on other players sometimes can't be seen

**Comment by xXNiceYT** [comment]
Beacon only gives me effect within radius must be some issues with your plugin. I don’t control what WDPE, if they can’t see the rain seems like wdpe issue to me not this plugin.
