### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by incharon093** [CLADevs/VanillaX#18]
Line 18 I'm bug

**Comment by xXNiceYT** [comment]
What do you mean by that?

**Comment by incharon093** [comment]
Error line 18 in vanillax.php

-> "public static VanillaX $instance;"

My server is error in line 18
You can fix?

ในวันที่ ส. 1 พ.ค. 2021 06:10 น. xXNiceYT ***@***.***>
เขียนว่า:

**Comment by xXNiceYT** [comment]
You are not using correct php version this plugin uses php 7.4 you are using 7.3
