### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ItsRealNise** [CLADevs/VanillaX#180]
![Screenshot_2022-05-08-22-20-48-545_com estrongs android pop](https://user-images.githubusercontent.com/90197402/167303151-d085d489-0feb-49c0-8171-8e92ce25a695.jpg)

**Comment by PocketMiner92** [comment]
ItsRealNise should Rename into = ItsStupidShit

Pocketmine User

**Comment by JustStevee** [comment]
> ItsRealNise should Rename into = ItsStupidShit
> 
> Pocketmine User

PocketMiner92 should rename into = Very Stupid PowerNukkit's User With Little Brain

**Comment by ghost** [comment]
bug

**Comment by hausemaster3734** [comment]
> ItsRealNise should Rename into = ItsStupidShit
> 
> Pocketmine User

СУКА ЗАВАЛИ ЕБАЛО ШЛЮХА ЕБАНАЯ ЧЕРТИЛА ЕБАНАЯ ХУИЛА ЕБАНАЯ Я ТВОЮ МАМУ НАОБОРОТ АААААААААА В РОТ

**Comment by ItsRealNise** [comment]
> ItsRealNise should Rename into = ItsStupidShit
> 
> Pocketmine User

lmao thats bug

**Comment by ItsRealNise** [comment]
And Bug Many XP drop in furnace smelting
