### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GamerMJay** [CLADevs/VanillaX#181]
if i take an enchant book example loot 5 and put the book on a pickaxe the pickaxe has loot 5

**Comment by PocketMiner92** [comment]
Another Idiot is Spawning

**Comment by GamerMJay** [comment]
wtf

**Comment by xXNiceYT** [comment]
What?

**Comment by AGTHARN** [comment]
what

**Comment by GamerMJay** [comment]
![Bug](https://user-images.githubusercontent.com/66413999/168092652-15bc52ad-253f-4384-84a0-d4fdd2adc678.gif)

**Comment by ItsRealNise** [comment]
> ![Bug](https://user-images.githubusercontent.com/66413999/168092652-15bc52ad-253f-4384-84a0-d4fdd2adc678.gif)

this bug in piggycustomenchant

**Comment by xXNiceYT** [comment]
Not related to this plugin
