### ISSUE TITLE
Connection to the server almost impossible

### ISSUE THREAD

**Issue by iBalix** [CLADevs/VanillaX#185]
When I use VanillaX it works perfectly but when my server is on for 6/7 hours it becomes almost impossible to connect to it, it takes 5/10 minutes to connect from a phone and sometimes it just crash.

Players get stuck on the "server search" screen.

When I remove VanillaX I have no more problems.

Do you have an idea?

Thank you.

**Comment by MonoAdrian23** [comment]
Stop use this and you have No problems

**Comment by xXNiceYT** [comment]
nope its not vanillax
