### ISSUE TITLE
Question about inventory security for the enchantment table and anvil.

### ISSUE THREAD

**Issue by Refaltor77** [CLADevs/VanillaX#186]
>Hello! Already thank you for your plugin it is just too well done, it deserves its place in the featured poggit ;)

## Now my question
I intend to use the plugin for my server, but having already experienced a lot of duplication concern with the magic tables and anvils before, I wonder if this plugin also has bugs ?

I saw that there was a check with the inventory transactions but I’m not sure that this is enough if the client disables the packets (especially on horion)

Thank you for your reply as soon as possible !

**Comment by xXNiceYT** [comment]
I’m currently not sure about the security measurement myself, I will try giving myself items with horion To see if it works whenever I code again. Currently I’m busy with school and exams

**Comment by Refaltor77** [comment]
Don’t worry, good exams!

**Comment by xXNiceYT** [comment]
This should be added now :)
