### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GamerMJay** [CLADevs/VanillaX#187]
hello, i have a sword with burning. When I kill a cow, it's raw meat, not fried

**Comment by NopeNotDark** [comment]
Not a bug, pocketmine it self only sets the entity on fire but doesnt change the drops if certain entitys die

**Comment by NopeNotDark** [comment]
You can also set an entity on fire using flint and steel and it wont drop it cooked / fried,

**Comment by NopeNotDark** [comment]
I dont get that, i get the items as cooked

**Comment by xXNiceYT** [comment]
This might not be a bug since @NopeNotDark said he tested it but ill check it out too.
