### ISSUE TITLE
🐛 » Bug

### ISSUE THREAD

**Issue by SlidexDE** [CLADevs/VanillaX#188]
Hello!
First of all I want to say that you read very good work on the "VanillaX" plugin.

Unfortunately, the enchantments are not carried over at the enchantment table. By that I mean that when I buy an enchantment, it's there for a second and goes away right away.

I would be very happy if you could fix this error.

**Comment by TheSavageDude** [comment]
this issue works, but after you use the item once u can enchant the item.

**Comment by SlidexDE** [comment]
> this issue works, but after you use the item once u can enchant the item.

Ok, thank you!

**Comment by xXNiceYT** [comment]
I’ve heard that new inventory transaction system should be added to fix this, which pmmp will do themselves.
