### ISSUE TITLE
Enchant Bug

### ISSUE THREAD

**Issue by xS91D** [CLADevs/VanillaX#189]
Doesn't work

Video:

https://youtu.be/EuFS3i86pvw

**Comment by ghost** [comment]
Most likely, you do not have an enchantment table included in your `blocks.yml`  Enable it in `plugin_data/VanillaX/features/blocks.yml`


![изображение](https://user-images.githubusercontent.com/60012371/173182529-aee97919-1ebd-40d7-bea2-aea27e36d21d.png)

**Comment by xodamcm** [comment]
Yeah this doesn’t work, with 1.19!

**Comment by xodamcm** [comment]
https://youtu.be/afa4oqjIw2o

**Comment by xXNiceYT** [comment]
duplicate #188
