### ISSUE TITLE
Netherite bug

### ISSUE THREAD

**Issue by TheBrayanYt4056O** [CLADevs/VanillaX#191]
Netherite items are bugged as they can kill you with 2 swords having strong enchantments
Please fix this is the best plugin!

**Comment by xXNiceYT** [comment]
? what

**Comment by TheBrayanYt4056O** [comment]
> ? what



> ? what

The netherite armor and sword are bugged when someone full diamond and you are full netherite kills you in just 2 hits the one who brought diamond please fix it

**Comment by xXNiceYT** [comment]
can u do a video for me?

**Comment by TheBrayanYt4056O** [comment]
> can u do a video for me?

Sorry for spanish @xXNiceYT 

https://youtu.be/eh7uDdC5E9w

**Comment by xXNiceYT** [comment]
Probably something your server, it modifies the damage.

**Comment by TheBrayanYt4056O** [comment]
> Probably something your server, it modifies the damage.

No, in others servers is bug netherite

**Comment by xXNiceYT** [comment]
Will check again
