### ISSUE TITLE
FilterTextPacket Error ?

### ISSUE THREAD

**Issue by Kan9TK** [CLADevs/VanillaX#193]
I don't know it's a minecraft error, but not getting FilterTextPacket.
so normal items are renamed well, but enchanted items are not.

**Comment by xXNiceYT** [comment]
Will check

**Comment by Kan9TK** [comment]
Also, is it inevitable that item nbt is initialized when enchanting?..

**Comment by xXNiceYT** [comment]
what you mean by that? anvil only changes the customName variable in the nbt thats all

**Comment by Kan9TK** [comment]
Enchanting. I edited lore&name to test enchanting but initialized except for enchantments
![image](https://user-images.githubusercontent.com/82082011/180050453-53c34322-f5e4-4650-be22-36895d6402e3.png)
![image](https://user-images.githubusercontent.com/82082011/180050506-24bd103e-f028-4c90-893a-369f20fdb9c1.png)

**Comment by xXNiceYT** [comment]
yeah its client sided

**Comment by Kan9TK** [comment]
ok thanks! Finally, if make it rain one world and teleport another world, the rain doesn't stop.

**Comment by xXNiceYT** [comment]
Okay
