### ISSUE TITLE
Inventory Error?

### ISSUE THREAD

**Issue by Kan9TK** [CLADevs/VanillaX#199]
There is no error log, but it seems to neutralize InvMenu's Transaction Listener.
This was not the case in previous version.

**Comment by xXNiceYT** [comment]
well i recomm you to use the old ver, this one implements new inventory system which was added in 1.16, pmmp will add that themselves soon, i just did it myself because there was alot issues with enchantment, anvil and smithing table.

**Comment by xXNiceYT** [comment]
[VanillaX-4.0 (13).zip](https://github.com/CLADevs/VanillaX/files/9194806/VanillaX-4.0.13.zip)
You can download this, this is the version without new inventory transaction.
