### ISSUE TITLE
[Suggestion] Enable / Disable that we want to work in config.yml

### ISSUE THREAD

**Issue by UnEnanoMas** [CLADevs/VanillaX#20]
For example if we want the elytras to work, or the enchantment table to work.

This is done so that plugins are not mixed.

For example the one from ArmorStandExpanded (which is very complete) with the armorstand that this plugin has (which you have not added yet)

**Comment by xXNiceYT** [comment]
I wasn’t gonna add that option since I just added armor stand right now lmao

**Comment by xXNiceYT** [comment]
Lastly it would be annoying to add option to disable every item they would like to disable or enable

**Comment by UnEnanoMas** [comment]
https://github.com/CortexPE/TeaSpoon/blob/master/resources/config.yml

https://github.com/XenoServers/TableSpoon/blob/master/resources/config.yml

The differences between these plugins and this one is that it can be deactivated, giving the player the freedom to choose what to activate and what not to activate.

I suppose that many will not use it because they do not have this, I include myself

**Comment by xXNiceYT** [comment]
I understand where you are coming from, a lot of people would like to enable/disable of feature. ArmorStand is considered to be an entity so toggling mobs to false in config should unregister ArmorStand too, but let say we do add ArmorStand toggle ability to Config, other people might suggest to toggle Vex Entity off you know we can’t just add each entities it would take long but I’ll think about it. If it seems like a good idea I would do it

**Comment by UnEnanoMas** [comment]
It takes a long time and it's worth it, and I'm not just saying it for armor extand, for example if you add beacons, because there are also beacon plugins that are more configurable and you may want to disable the beacon of your plugin.

What I mean is that you do not force the players to use something they do not want, since your complement brings many things, maybe there are people who want to deactivate x things because they are not going to use them

**Comment by xXNiceYT** [comment]
Will add em in future
