### ISSUE TITLE
Two Crash issues on the new build 

### ISSUE THREAD

**Issue by JoshuaPHYT** [CLADevs/VanillaX#200]
i just updated the plugin to the latest version. now my server is crashing (this is not happening before)
[Wed_Jul_27-04.23.30-CEST_2022.log](https://github.com/CLADevs/VanillaX/files/9194932/Wed_Jul_27-04.23.30-CEST_2022.log)
[Wed_Jul_27-05.40.52-CEST_2022.log](https://github.com/CLADevs/VanillaX/files/9194933/Wed_Jul_27-05.40.52-CEST_2022.log)
g

**Comment by xXNiceYT** [comment]
Its just same crash ill look into it tho

**Comment by xXNiceYT** [comment]
hey can you try it with latest version

**Comment by JoshuaPHYT** [comment]
I think it will not crashed anymore. Thanks

But there is another issue Mending is not working the time I updated to the latest build

**Comment by JoshuaPHYT** [comment]
https://medal.tv/games/minecraft/clips/u6s2afttiVRLc/d1337sDhBJgo?invite=cr-MSxwRmssMTMxNzIyNTAs
