### ISSUE TITLE
Other Plugin that uses Inventory is broken

### ISSUE THREAD

**Issue by JoshuaPHYT** [CLADevs/VanillaX#202]
So the time I update the Vanila X plug-in to the latest Dev build. 

Other plugins is affected such as Auction House, Crates plugin and etc plugin that uses Inventory system 

You can get the items. Which is not their plugin fault. It was fixed before I updated the Vanila X. 

https://user-images.githubusercontent.com/69298936/181632736-ad8d038f-c997-48c3-86e6-6fd67ac4e518.mp4

**Comment by xXNiceYT** [comment]
This can't be fixed due to the latest version using the new inventory system. use old build if u want other inventories to work.
#199
