### ISSUE TITLE
Crash 4.7.0

### ISSUE THREAD

**Issue by ZippingBoat9588** [CLADevs/VanillaX#206]
![Screenshot_2022-08-13-21-14-03-609_com discord](https://user-images.githubusercontent.com/104681534/184507753-b44b7066-b734-447f-9f44-f265452fd1c5.jpg)
fix pls @edwinyoo44 @iiFlamiinBlaze @xXNiceYT @hausemaster3734

**Comment by xXNiceYT** [comment]
FIxed on latest one https://github.com/CLADevs/VanillaX/commit/cb0a2d5dd175197b2d356d7ebf89d9379d0db98e
