### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by GamerMJay** [CLADevs/VanillaX#207]
2022-08-13 [22:03:27.011] [Server thread/CRITICAL]: InvalidArgumentException: "Enchantment does not have a mapped ID" (EXCEPTION) in "pmsrc/src/data/bedrock/EnchantmentIdMap" at line 91
--- Stack trace ---
  #0 pmsrc/src/item/Item(349): pocketmine\data\bedrock\EnchantmentIdMap->toId(object CLADevs\VanillaX\enchantments\types\PowerEnchantment#101079)
  #1 pmsrc/src/item/Item(237): pocketmine\item\Item->serializeCompoundTag(object pocketmine\nbt\tag\CompoundTag#164408)
  #2 pmsrc/src/item/Item(229): pocketmine\item\Item->getNamedTag()
  #3 pmsrc/src/network/mcpe/convert/TypeConverter(142): pocketmine\item\Item->hasNamedTag()
  #4 pmsrc/src/network/mcpe/InventoryManager(322): pocketmine\network\mcpe\convert\TypeConverter->coreItemStackToNet(object pocketmine\item\ItemBlock#164407)
  #5 (): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}(object pocketmine\item\ItemBlock#164407)
  #6 pmsrc/src/network/mcpe/InventoryManager(323): array_map(object Closure#164405, array[27])
  #7 pmsrc/src/network/mcpe/InventoryManager(194): pocketmine\network\mcpe\InventoryManager->syncContents(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164183)
  #8 pmsrc/src/network/mcpe/InventoryManager(178): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
  #9 pmsrc/src/network/mcpe/InventoryManager(199): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#164400)
  #10 pmsrc/src/player/Player(2502):

**Comment by xXNiceYT** [comment]
Which version and how did u cause this?

**Comment by GamerMJay** [comment]
The one from before 4 p.m

**Comment by xXNiceYT** [comment]
This repo only stays up to dated w latest version
