### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ZippingBoat9588** [CLADevs/VanillaX#208]
If i Spawn a Mob Like Chicken my Server crash If i restart and try to Join its keep crashing pls fix it thx

**Comment by xXNiceYT** [comment]
Whats error

**Comment by ZippingBoat9588** [comment]
@xXNiceYT 
[Tue_Aug_9-23.56.03-CEST_2022.log](https://github.com/CLADevs/VanillaX/files/9409141/Tue_Aug_9-23.56.03-CEST_2022.log)

**Comment by xXNiceYT** [comment]
How do I reproduce this error

**Comment by ZippingBoat9588** [comment]
@xXNiceYT If you Spawn a Mob i Spawn a chicken

**Comment by xXNiceYT** [comment]
Can't reproduce it
