### ISSUE TITLE
InventoryTransactionEvent not working

### ISSUE THREAD

**Issue by FurkanYks** [CLADevs/VanillaX#210]
inventorytransactionevent not working with VanillaX i mean event is not cancelling with this plugin and i cant use Muqsit's inventory menu readonly function is not working.

**Comment by xXNiceYT** [comment]
VanillaX uses new inventory system, use older version currently this branch uses new inventory system

**Comment by xXNiceYT** [comment]
https://github.com/CLADevs/VanillaX/issues/199
