### ISSUE TITLE
Fatal Error BUG

### ISSUE THREAD

**Issue by TheBrayanYt4056O** [CLADevs/VanillaX#211]
When I put e vanillax I restart the server and it gives me that error, if it lets me enter the server but does not let me execute commands on the console and there are bugs
![image](https://user-images.githubusercontent.com/103159470/186281832-5a3f2f0b-6b01-495d-a5f3-cb67f2e8839d.png)

**Comment by xXNiceYT** [comment]
Redownload ur php(bin) it’s ur php fault not the plugin itself
