### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hawwjla** [CLADevs/VanillaX#213]
Fatal error: Declaration of CLADevs\VanillaX\inventories\utils\TypeConverterX::createInventoryAction(pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction $action, pocketmine\player\Player $player, pocketmine\network\mcpe\InventoryManager $inventoryManager): ?pocketmine\inventory\transaction\action\InventoryAction must be compatible with pocketmine\network\mcpe\convert\TypeConverter::createInventoryAction(int $protocolId, pocketmine\network\mcpe\protocol\types\inventory\NetworkInventoryAction $action, pocketmine\player\Player $player, pocketmine\network\mcpe\InventoryManager $inventoryManager): ?pocketmine\inventory\transaction\action\InventoryAction in phar:///var/lib/pufferpanel/servers/e41c6470/plugins/VanillaX_PM4.phar/src/CLADevs/VanillaX/inventories/utils/TypeConverterX.php on line 33

**Comment by hawwjla** [comment]
using nethergames compiled pocketmine phar

**Comment by MonoAdrian23** [comment]
This Plugin is only supported for Official Pocketmine!

**Comment by xXNiceYT** [comment]
Can't do anything or it will ruin compatibility with normal pocketmine
