### ISSUE TITLE
[Bug] Inventory bug

### ISSUE THREAD

**Issue by LordBombardir** [CLADevs/VanillaX#217]
PMMP 4.10.0

When laying out things in the inventory, the player crashes.

https://user-images.githubusercontent.com/60620262/199212196-85794aa8-536c-474d-83b8-abdafad399f5.mp4

When throwing things out of the inventory, they are thrown out all (Despite the fact that 1 item should be thrown out).

https://user-images.githubusercontent.com/60620262/199213368-d4135d0f-f9f3-4e9b-98a8-5a2283f2b7bb.mp4

![image](https://user-images.githubusercontent.com/60620262/199213454-20e8a65f-42ba-4e82-9949-460597279807.png)

and
![image](https://user-images.githubusercontent.com/60620262/199214464-beae8b47-7b4f-4f4d-a4c6-3327e85e6d82.png)

**Comment by xXNiceYT** [comment]
Should be fixed in latest version.
