### ISSUE TITLE
Container ID Error

### ISSUE THREAD

**Issue by Nisekoi6800** [CLADevs/VanillaX#220]
[00:27:33.815] [Server thread/CRITICAL]: Exception: "Failed to find container with id of 60" (EXCEPTION) in "plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler" at line 457
--- Stack trace ---
  #0 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(463): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->getInventory(int 60)
  #1 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(169): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->getItemFromStack(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#408624)
  #2 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(135): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->move(int 0, object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#408624, object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#408627, int 64)
  #3 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(78): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->handleTake(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\TakeStackRequestAction#408620)
  #4 plugins/VanillaX-4.0/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(217): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#394546)
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/ItemStackRequestPacket(55): CLADevs\VanillaX\network\handler\InGamePacketHandlerX->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#394546)
  #6 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\ItemStackRequestPacket->handle(object CLADevs\VanillaX\network\handler\InGamePacketHandlerX#395069)
  #7 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#394546, string[63] ...Y..(......... .........___Meta___...............@<2Y;.......)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[92] ........!.8....a......\...\......%.@....028..EZ.Y...d....;.....f..s..mw..0. q.F&)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[101] .....n...WsQwB...w.gS..c.-].W.....e.......U.y.p..R%a..8..6..VW.=.'.$H....8....c.)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#371800)
  #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1670088453.8289)
  #14 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[8] D:\PMMP\, string[16] D:\PMMP\plugins\)
  #16 pmsrc/src/PocketMine(351): pocketmine\server()
  #17 pmsrc(11): require(string[52] phar://D:/PMMP/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by xXNiceYT** [comment]
how do i cause this error

**Comment by Nisekoi6800** [comment]
> how do i cause this error

When moving items in inventory (PM 4.12)

**Comment by Nisekoi6800** [comment]
for more details:
https://user-images.githubusercontent.com/85490084/205840116-e6268439-5c18-4c34-b3e3-6e600c854fe2.mp4

**Comment by TukangM** [comment]
#217 #219 may caused by this (after fixing code of VanillaX)

**Comment by TukangM** [comment]
it fixed?. im having issue. but i think i dont update the pl

**Comment by TheLemzz** [comment]
still not working.

**Comment by xXNiceYT** [comment]
> still not working.

use the new pmmp version it fixes the issue, it was issue wit pmmp not this plugin
