### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by NekoFuwa1739** [CLADevs/VanillaX#222]
`[22:45:15.287] [Server thread/CRITICAL]: Exception: "Failed to find container with id of 47" (EXCEPTION) in "plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler" at line 457
--- Stack trace ---
  #0 plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(463): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->getInventory(int 47)
  #1 plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(161): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->getItemFromStack(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#208779)
  #2 plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(144): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->move(int 1, object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#174959, object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#208779, int 1)
  #3 plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/ItemStackRequestHandler(80): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->handlePlace(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\PlaceStackRequestAction#205444)
  #4 plugins/Bedrock.phar/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(217): CLADevs\VanillaX\network\handler\ItemStackRequestHandler->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#205386)
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/ItemStackRequestPacket(55): CLADevs\VanillaX\network\handler\InGamePacketHandlerX->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#205386)
  #6 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\ItemStackRequestPacket->handle(object CLADevs\VanillaX\network\handler\InGamePacketHandlerX#130639)
  #7 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#205386, string[18] ...q....../.......)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[66] ....X...(..........'0.8....+..+.*...ov.b)tf...xCC.....n9.....{.T..)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[75] ..<...Xf.:=Y}..z.sid.......wS.i.(.dl..9_".....u...~..d....T..f^....qG.E.&..)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#164177)
  #11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1754): pocketmine\snooze\SleeperHandler->sleepUntil(float 1671198315.2993)
  #14 pmsrc/src/Server(1102): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[28] /home/kuroneko5159/nekosaba/, string[36] /home/kuroneko5159/nekosaba/plugins/)
  #16 pmsrc/src/PocketMine(351): pocketmine\server()
  #17 pmsrc(11): require(string[72] phar:///home/kuroneko5159/nekosaba/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---`

**Comment by xXNiceYT** [comment]
Try new pocketmine it should work fine
