### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ItsRealNise** [CLADevs/VanillaX#223]
VanillaX cannot use encahnting table, anvil, smithing table in waterdog pe?

**Comment by ItsRealNise** [comment]
is not working on waterdog pe lastest version of VanillaX

**Comment by xXNiceYT** [comment]
Does plugin load? Waterdog shouldn’t really affect it

**Comment by ItsRealNise** [comment]
plugin load, idk why its not working

**Comment by xXNiceYT** [comment]
idk it works fine with pocketmine for me

**Comment by ItsRealNise** [comment]
maybe cause with waterdog extra injector or waterdog fix crash?

**Comment by xXNiceYT** [comment]
Can you try joining on main server without joining through proxy and seeing if it works.

**Comment by ItsRealNise** [comment]
okay i will try

**Comment by ItsRealNise** [comment]
on my server it doesn't work (usually if you just joined the initial server/main lobby it works whereas if you move to the survival server it can't)

**Comment by ItsRealNise** [comment]
@xXNiceYT

**Comment by ItsRealNise** [comment]
like you, for example, enter the server, initially on the lobby server/main server, but if you change the main server to survival, then you can, I don't know how to explain it, but vanillax can only be at the beginning, which server we enter first and if you transfer to another, it can't be done anymore

**Comment by xXNiceYT** [comment]
wdym

**Comment by xXNiceYT** [comment]
join the server without using proxy ip and see if vanillax works there

**Comment by ItsRealNise** [comment]
> join the server without using proxy ip and see if vanillax works there

if works on main lobby not in another server and i move ip lobby config wdpe to survival is working idk
