### ISSUE TITLE
Update For PMMP 4.16.0 and 4.17.0 

### ISSUE THREAD

**Issue by xS91D** [CLADevs/VanillaX#226]
Error: file_get_contents(phar:///root/main/PocketMine-MP.phar//item_id_map.json): Failed to open stream: phar error: "/item_id_map.json" is not a file in phar "/root/main/PocketMine-MP.phar"

Error: file_get_contents(phar:///root/main/PocketMine-MP.phar//block_id_map.json): Failed to open stream: phar error: "/block_id_map.json" is not a file in phar "/root/main/PocketMine-MP.phar"

**Comment by khIbrahim** [comment]
https://github.com/khIbrahim/VanillaX

try this one untill they solve it ( dont forgot to use the main one once they fix it )

**Comment by Ardaa001** [comment]
> https://github.com/khIbrahim/VanillaX
> 
> try this one untill they solve it ( dont forgot to use the main one once they fix it )


There is a bug in the plugin you fixed

**Comment by Ardaa001** [comment]
@khIbrahim 

There is a bug in the plugin you fixed
