### ISSUE TITLE
Ender Dragon and API 4

### ISSUE THREAD

**Issue by TheBalkanDev** [CLADevs/VanillaX#23]
I saw the EnderDragonEntity file and I tried to summon this but it don’t works in any way.
(I tried in API 3.19.1)
And can you maybe Update this Plugin to API 4?

**Comment by xXNiceYT** [comment]
How did u spawn it?

**Comment by TheBalkanDev** [comment]
This it the Problem... it don’t work.
I’ve tried with many Plugins to spawn him but it didn’t work.

**Comment by TheBalkanDev** [comment]
I tried with my own Summon Plugin, I tried it with PEX.
It don’t works

**Comment by xXNiceYT** [comment]
if ur a developer and want to spawn the entity its ``$entity = new EnderDragonEntity($world, EnderDragonEntity($position));
$entity->spawnToAll();`

**Comment by TheBalkanDev** [comment]
I will try it
