### ISSUE TITLE
Brewing

### ISSUE THREAD

**Issue by xSuperr** [CLADevs/VanillaX#24]
When a potion is brewed, the ingredient does not get subtracted, as well as some potion recipes not working.

**Comment by xXNiceYT** [comment]
Hm could you be little more specific about which potion isn’t working?

**Comment by xXNiceYT** [comment]
Lastest commit fixes it whoops labeled it #2 instead of #24 Lmao

**Comment by xSuperr** [comment]
I would have to go through every potion, but I know that speed potions do not brew (Sugar-> Akward). I haven't tested it on the newest commit though.

**Comment by xSuperr** [comment]
Also when adding gunpowder to a potion, the potion turns into a splash water bottle and not the original potion in splash form.

**Comment by xXNiceYT** [comment]
All issues should be resolved
