### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by MrNinja008** [CLADevs/VanillaX#29]
If players break a block it doesn't drop when i uploaded this plugin. Not the blocks you add i mean all blocks in server like dirt sand etc

**Comment by xXNiceYT** [comment]
Hm how are you breaking the money?

**Comment by MrNinja008** [comment]
> Hm how are you breaking the block?

By pick and tools and also in hand i mined dirt it dosnt drop :/

**Comment by xXNiceYT** [comment]
It seems to be ur plugin issue then, seems to work fine on my servers.
