### ISSUE TITLE
cant load

### ISSUE THREAD

**Issue by efor89** [CLADevs/VanillaX#3]
hi i have this error onload

arseError: "syntax error, unexpected 'VanillaX' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/VanillaX" at line 15

**Comment by xXNiceYT** [comment]
You most likely arent using the lastest version

**Comment by efor89** [comment]
same error i use dev #25

**Comment by efor89** [comment]
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'VanillaX' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/VanillaX" at line 15
[15:09:31] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[25] CLADevs\VanillaX\VanillaX)
[15:09:31] [Server thread/CRITICAL]: #1 (): BaseClassLoader->{closure}(string[25] CLADevs\VanillaX\VanillaX)
[15:09:31] [Server thread/CRITICAL]: #2 (): spl_autoload_call(string[25] CLADevs\VanillaX\VanillaX)
[15:09:31] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginManager(167): class_exists(string[25] CLADevs\VanillaX\VanillaX, boolean 1)
[15:09:31] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[73] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\VanillaX.phar, array[2])
[15:09:31] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1530): pocketmine\plugin\PluginManager->loadPlugins(string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
[15:09:31] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[52] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\, string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
[15:09:31] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(303): pocketmine\server()
[15:09:31] [Server thread/CRITICAL]: #8 pmsrc(11): require(string[107] phar://C:/Users/Dennis/Desktop/PocketMine-MP-minigames-hub/PocketMine-MP.phar/sr)
[15:09:31] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[15:09:31] [Server thread/EMERGENCY]: Please upload the "C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\crashdumps/Fri_Jan_15-15.09.31-GMT_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by efor89** [comment]
PocketMine-MP Crash Dump Fri Jan 15 15:11:32 GMT 2021

Error: syntax error, unexpected 'VanillaX' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/VanillaX.phar/src/CLADevs/VanillaX/VanillaX
Line: 15
Type: ParseError

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[6] use CLADevs\VanillaX\enchantments\EnchantmentManager;
[7] use CLADevs\VanillaX\entities\EntityManager;
[8] use CLADevs\VanillaX\items\ItemManager;
[9] use CLADevs\VanillaX\session\SessionManager;
[10] use pocketmine\plugin\PluginBase;
[11] use ReflectionException;
[12] 
[13] class VanillaX extends PluginBase{
[14] 
[15]     private static VanillaX $instance;
[16] 
[17]     private EntityManager $entityManager;
[18]     private BlockManager $blockManager;
[19]     private ItemManager $itemManager;
[20]     private SessionManager $sessionManager;
[21]     private EnchantmentManager $enchantmentManager;
[22] 
[23]     public function onLoad(): void{
[24]         @mkdir($this->getDataFolder());
[25]         self::$instance = $this;

Backtrace:
#0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[25] CLADevs\VanillaX\VanillaX)
#1 (): BaseClassLoader->{closure}(string[25] CLADevs\VanillaX\VanillaX)
#2 (): spl_autoload_call(string[25] CLADevs\VanillaX\VanillaX)
#3 pmsrc/src/pocketmine/plugin/PluginManager(167): class_exists(string[25] CLADevs\VanillaX\VanillaX, boolean 1)
#4 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[73] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\VanillaX.phar, array[2])
#5 pmsrc/src/pocketmine/Server(1530): pocketmine\plugin\PluginManager->loadPlugins(string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
#6 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[52] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\, string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
#7 pmsrc/src/pocketmine/PocketMine(303): pocketmine\server()
#8 pmsrc(11): require(string[107] phar://C:/Users/Dennis/Desktop/PocketMine-MP-minigames-hub/PocketMine-MP.phar/sr)

PocketMine-MP version: 3.17.1 [Protocol 422]
Git commit: 260c55f23a7c630a43f264d94de0b31e5327263d
uname -a: Windows NT DESKTOP-ORFVSSK 10.0 build 19041 (Windows 10) AMD64
PHP Version: 7.3.19
Zend version: 3.3.19
OS : WINNT, win
Composer libraries: 
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
- daverandom/callback-validator unknown@unknown
- pocketmine/binaryutils 0.1.12@566fa87829e007eda0bd96e39fe20b9b0d638132
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.1.1@7c0363491d1ce8f914fe96d41a4338c982adedff
- pocketmine/log 0.2.0@e59bedb5d4bbeb9a26647cb7c367cb2fa72addfa
- pocketmine/log-pthreads 0.1.1@9bbcef398b01487ab47c234a6a7054722abbe067
- pocketmine/math 0.2.5@8c46cfa95351fb0b2b30739a381310941934b55f
- pocketmine/nbt 0.2.15@f8a81d37d24eb79fb77d985a52549d68955bc6a1
- pocketmine/pocketmine-mp 3.17.1@260c55f23a7c630a43f264d94de0b31e5327263d
- pocketmine/raklib 0.12.9@5f2a02009f486ca4d90892814570fa13ebdc078d
- pocketmine/snooze 0.1.3@849510fa62e57512b8467e3694e9b3add97038fd
- pocketmine/spl 0.4.1@ff0579a0be41bbe65d3637607715c0f87728a838

Loaded plugins:
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
CityBuildCommands 1.0.0 by efor89 for API(s) 3.0.0, 4.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
SignCommand 1.0.0 by  for API(s) 3.0.0, 4.0.0
CommandLogger 1.0.0 by  for API(s) 3.0.0
Perks 2.0.0 by efor89 for API(s) 3.0.0, 4.0.0
BlueReport 1.3 by Plasma for API(s) 3.7.0

**Comment by efor89** [comment]
===BEGIN CRASH DUMP===
eNrtW4lv28aa/1dmlWIbLySZhyRKKlwk9fHq1zj2xkrz8OrCGJJDic+8ysO2WvR/39/3zVCiZKdt
tsHiYdGghcg5vvscjn/pRXmZyvr2XpVVnGe9+ajfq+NU9eb2xLY8xx3NnOHYtcc2JppCT1nD8cga
ue506k4mk9nMcfq9RFb1aVnmZW/+S69eF1jWu5JlpfRgv5eqqpJLGq7WWS0fhaKJvmgy9ViooFah
+PJ7mcVJIv/xpXi5uL1evDt/+7eDvtDzcbYUUZPhIc9o+uz92+PF+eXbA5GXIsizqqbR48u314sD
oIuaJDmLE8JXrGQ5Pzw8nh++r8Dm4YnKsph+qrs6Lw6v8uBO1RdxpgYXV4M0zuKlBLGDVeMfFkmz
jLPqsCVsSLAOqzI4PH7z+kTdb2e6SwrCb3B/OgBsTkAMNDCGLkoZ4PGH3gtLFCntu1dZmJeHBVMN
atVhANlXSS5DpSF/Iyt1TGNveOyl7YwO5mJvdPA17eCBl1VdQro/OOMfhaHq5qalZvtEUn1hi5fP
wfolSPKqKdWvnwLLYVhVkdzKps6JnNtAJsmngHCNUOj/jkS01A+v+OdCZrA7iGHiAR0L61Y9xlX9
RxnvCz/PEyUzYTPS0ScgdUcTIN2uurnRy25udtZpbeihlirPBVXzmxs22psbbbX0y2YLAB+32xZL
hx02vL6QZSnXPzg/MiPj5xm5VuU9yWvsWp9K+0akE+tzEM9UTp6ncgvhpeM5e4RqFgZf395yZCib
oH6Z+/9CGNm33b4w493tTR0nQH8h4+xNvlzSKsPX2PkTfG2gfEbpeL8rHddy96RTaQXz/qne/9K2
sahUPzVxqVolIgH8KP5E9NyZayPfQe/HX/s99e+UKj5HqAZPGsBtnN3nyb1KVVYDagh5BjUWBnmo
iOEJBptKPRdwVBasZFbTToyfbt+Mp30FMN5vba/jOla8FU/rzq7px3fFtUoxcI6fzobZxzdU0A4E
S07GD51dtmW2fTxokPvxUtssfaeiRLGqTh8DVdADzzuYp18Xvxy0RUsCtFwjCVZiC/EXWjkyO8b4
FfhXlPG9rBWcTtZxsN3+BbRcyyzQdEzMLm9v144MxRdqX6T2dG/DNwmY3qz3O2+8fLa3vCNwULQr
fcfaW7wravFF9UT0jv2E/n3zISaeMynHiNpxWxCNn0BgGxfKM4qVlKzv8zgkWTsjs5T+vUrvYOUv
v6hXcTX4eqnqE1nLszyh2uPggDGMO8srlUTz+UYJ4kjwzq96v/5V7vxV7vxV7vxV7vw/K3f6vaXK
VCkTSv+ZTLne6a4FYT7UtG3Ce+7Q9oY2jTdxEqK+mDrov+PqNlT3vXkkk0qh3ijzOg9ygB1RB76M
qd5wJlYwHkeOK71g4lpy5EbOZBTORqGyfNdWYxfmM3FDwG4MLR9ihNiHSrxdiJPT6+8Wl1eDy3dn
319ffydsa2gJpkHYM2uEcNgutq0D8friZDICIOp45z1vCKpneP0ZIZt5MO+Yvs0rQnT+9u0CA/zy
EGdcFaVFDkHfJrFfyhLVCwlJhiswVqrDf1V5NsAaU0xZQ3tovZqORlPLm1juzJ3OovF4GrkzGVrj
sSulP/VC342m9sQmykIJmUpQnB5SrPVlcDe4l0kcyprKT4jgLssfslfml4jdGpUfZ7Jcs3MY3Lbz
ajyZRHLqTZ2ZsixPhdLyw9lEubNIOZY/861w4k5t19kF9Sxy8DJ0X01G3tQbTWbeZOIHUnpqPJ2O
nZGjpuPAcQNnrKZQqNwHuE2CLW2vvMByJ+5oZod2oKbRzB5FajYJR7aks5pgNnWwPIyiXUhJvmQI
DiSrxjNfhf44HPm+8mfSmYC6wPcCd4IfJ5IeQISRfAJhUNSrUslwI6hXM98PFBQz9S17NPWkD0CO
O5IT6Vnjkec4EiisibcLKpX1ylAzfjUNRpMgkrOxO7Yj3/Id37U8qJrka1uzkT1zRz5sfRdE5tcG
gj1+FU3l1A5dL3RGyvdmke954Ww6lmNnPJqFk+lsPPaDibR3QWwfB2mx8cZXn+BaHWClvINta7k4
w9krAJCWY1mzaDSdBBL7renMmdqjsWdF0naVHwaWN92DUmV5/rMy0nXhArOxjeUTR429se3409HE
U+5kNlIz34WOZp7lTqN9IEXCEEZgJoqssTeD9aqRDU1MxiFsB07lefY4sKKp5zmQnTvt/brpbNg1
r1D2XKkyrbrBbDPW721jmA08LkZQ7azysqKqbjI6O7Ms8Z/iqswpC51nESJovaYYKYuYlrhwCove
VSb9RIWbaBeqgop+rMFklUf1SXcgRe4CzluNASmlJanzSN0aPIYIvrxefLh89+YEQw/Kr1B+Y3RV
10WF2I9AinA+RNg55L2mL9zCgUSOm6rO09eJKuuuJHaGu8JwOJp3RHGKJvEaXHw21ruob272CDF8
Xy9ev1u8v3qW64eHh6ECUQR/WN8xk1DNNxT8jxGBJSPccvpkblf3xMoOwyrKy+nsCbv93ujPsd3S
AZ7bx99TNPFG2jxeyXrPjHlo34pt+zkz/jTNdZzkCTe9M8mNVgW3AKZ/qPs4b6qr00E73vuIhRO1
26fPYN8MBtK5aJI6/pCXVHts5NMZ3JXQeOjsCuj4ZxWsri6ow8DE9/FjfHf8Tz6URzqtmrsYz3fI
hPFd9dnsPyCcRRpyV5MSqQ9EKsraLtmfKqAOJ4cdQBDRdbzMjO13ZNQd/W2H+NyOEC9+PiuV+vYE
7UAFKgJNhS7r/4hHGLJ1B9D19J3xT2Pqf8vMt+tClWeJLNXFMRy7S8EfZwjedreTpvh9Nyr/X4Up
xg1XpZ/353+E+m+SRr1TRV52Q1RncFcRe4n2CuVhKne48D6Z+t5V/KgS7m8W+UlcoSIPO5FI47i5
0fS0v7/PGtUTsgTUWhlin/RNHCK5axuiyYEp1NwY9F5cbd7EcY7iYSno8PamvMleLFaN+HuTCEdY
IzREc2csvrleCAe1Fs0nMls26N+PQtXQe5rX4dFNY1nS879R4QdZVv9B4xrtgOR9hFr4AeOdYeLw
CI2G69IgiSbNQ3XEGFL5OCgSuQZXR6jveFchH7IB9Wn6hPNoYNPwwwqyGCRxVR/lUUQjWiuDnxpV
ro/yrDNUoqNvV9HzsEDhj8gWHv0X/7vJZJblTRYog3wgg1Ws9Plz1e6EUWPBhl4zCkmH1Ga178V9
YZCHcRTFAeLd+shhTrmBRdsyqFRN5+vVEQsVeBItKyPD7WilVNhZROf8RyenZ6/fv1nQKJ2BDSq0
ZwbjfaweBmGszwSP7AmNPfr544Cs2qzR4pRZnMJ2d8bS3G8Hdkre4TqlkveFoJhBR/8wmQaM0Kkm
WY6AYMSO/cGSxGKlKiVaTgWikKhXSuQZzK5GhhQBybwWvhJxFiQNuio8iCcWS7Cu8xQ7IwKwD7OS
keqLHDNlRSCFjxbqTqzzpjSwRBwJKCyOYsYAXdHHhGRNgN+qhw24w1BFEtqqxEOefVkLWRRKloJk
nNLZN7rPNVFI56ya74eVykRTLEsZAsDwJiMT18DmN5kQLz6sFBEm6hxYslAAhDnOgQzQUleJpO8w
PM2kJjnQKPrCkqia5YVUHAdKrBC6E5ZgSpC1KbbuOBcch2iiWjV1mJMy9eefubjp6YMtQcetKrzp
MWWvkyR/EOQ99J3HtCbiPpbiv8l9aA370cBMzUFvwxhenLJPmT0CdAkyfwGNQSgEzV8LI0pab1xw
M90h9sWHGALJM8gV3ZYoVaXFT2KFwO9EqiSdEJMXCgjdV0Q0hKN+amRCYlvG91h7LxHRxUuDFNHq
gKBrjHB+DqkDiJ0y3xzTjPttk/qQCqzqdbXOgoWs7qD48g52NOQF7yEtNu2WU1q2KnMECmgPy6u+
4OpIGMeGP/QFncWU+sMCywZBm8bSJoMF0RIN/JrVC55gZWX+CGesFcQAlthysw1xJFtD0HlEtkpr
yCb7Iq6/hPjqkreFisIjm8zeZvESPNBHIofFwmwMDKdzBrVvq5KNo2yyjNQZUujJC1YCn2JVQ4FS
zjyLNF6u4MylrFb9rvMZwyGJlGVT1HpUC4wEk4I2wxcrF07JR1ShdghJX0lA9vMUkI2QzeUQNKxr
2DE0LB7oRRtLQ1pByC7X2in/luQ+rIfStNDj8IM0rsm3U7WU/rqGxMW1FrXFwo0rgs3bF6S1h5gl
zxYFp30YaECtkVXMYRSDREQkUJ8xrAilZYtSGzm01ZCbimUOReXkpmQVhGjJZA6YtLmwiAtg5xCs
j4n+7TmgEue36KfM+efoR3teMAkmfG5IMuAqgfBBuR5xryWIsLZU2ZYzMoRxEPjAXmHoq778DBSy
XzBJFDFE0CD5ZEg+Qj2qoOHgm2uStUdSstqsVo8B8n+15UgHrsvF6Vwsvj2/Fm/OL84X4vXV1Zvz
02txdfpOoFb87vRdX2CRWFxi1an48O3lm1Nx9e7y+PT6ergfAnbk4YwnRhyoseOcEzIF4ooYDFaK
QzJLYxNsbcgeJUHIsYWXDBAKlQ6zDAo1JvhEgIY1Eb8fMzZtZCjrKAFmtMwgY8gaCELvNpDrjMQ4
LimHUJ7nDcOnq8kWTNUOtRUqoHJAS5bI1XrVezc8wLxUUW1ZdS3Da3XwPEmGc9dwvpSlD88YBHli
Ps5zAHpeuuxqRI7ZJcwuxG60bQ0XH11KUJg1sMGDfpsT9o2wNUOdXqMIsDS/6dYFh+JSx3xt8Kge
8iYJN7TESCIPmdjSX2nABZMPRieWZXgFtjMOFk+SJJuOhrDhLSrztE22erdZMeiaZlfDxI3R5BPb
EM+Y1I51XLcFI6msBCYyQ2PIYZMWurrSJZwwEwOaaPV1QovMBqadyWw5wBvSPJxdPiNgJG0kPmC4
h5FVVaMoMNQraG3ZVpsUtAjblqp+q0hdI5iicqipoaUflRP1T8Gqye6qlvZjWdBonDYpcizSayna
DoEUKXTDo6nYypX8xYiSPeapjaHYLgxFjHBAVXCDpDvaaOwk11P7Nq2vQ7Tw9eLWhTQss7DLGVcO
gwCNmdrwhn5a1yooH0l6oE4XGBpKIaknEXqP5nDLHbYZeWp+Wsy0eFvtkgATagMM3N8G9Vt2eJNl
qiaFzU2KQGm2yhNdYvqyRsNJlTiTjKoJJmSSDMc23fmYWZ1afLUpNnV6e9HVUjtFYbVc1wS8LwZ2
R4GsPEY8qFtiTArgqL2tY7n5pBIy1JxTL8OFPm3GoCFrKL5FLQhbOuLiThxfve9jL2jw4V8PcQiz
51pBR88N/AHDnwuvLbu3FXnF0umsHYrXIQLVSibRIVpJ3SaECjZsUAGpoLMTMrCOI27TXgdYtxU5
faSoRiWmTPo6aBJq86V2KBYl54ucK+n3V9lVW4dve0NqM2jTAzIqwWyKrBiY973G58I4ZBX/rDaq
poq91XBFudBUU6joteV0su5o5uhNB0NxZfYkslzyBmmaVGMmjDEq5ZK4g7rAVlUkXMxQ55mCeIoD
siQVHicxnXlwK02f9lVVi4vFe6a0AkvEtt/Uglp31vIWne47hm0YSutmQLvmTC05QKj8Zjlve5mv
hU09jKnkVvBinhemc610r634rmGuc5oxFJuA6biloR2vcvS2ZJxtC6PaJpWDWyhrKSp53wZROjJp
T3pobuvvEjkdkUDJuo0xoFSf8rUlM7dbMCEuV6oCFRqXL1keJHEheC/keCHXkCEZS5rftx0shX8T
MzluDdo5jbLaRov2+Kd7mrDg4wBtAPovDvRBCq812m4qcywRwOprHRfMnoHeMxcFCor7OCE0OuYZ
fzZYKGjLbLkpqjPaluznjn67aufM6dkTHN3lvU7zhmw60sHZmDiJUh/3cTIid+beHYqhZ84m2PyO
c0tnMzOeKd0r+koD8+ncGc90msXpYNVaACudD7l2spRmnxBt2IdnCrlPKngJOMwKhQTwHJXW82TK
EpBgH60hgth2M/1uqHHZuqmTHjQFLFJVnWgRUAJiRHzc2TmKOT9hZHxNsmKXJHmqkjQt9JUNYbgT
5uShzXa8Z4d1wBsIR7wQS/Qs1VY829ONjYSGT0VknPVBxtzUIHCg4te6KfKiSVpjNC8U9nmNCREu
BwiuhgeFcWuKruSpc9HWmXzeqc9z5ibj0fET91h6WCcMoy8Qsj0YCLdyI3sf0FXivaGNu+0OFyuU
ZlHe0Qi8bKC/c21WrnLSDJMyLNK0GMY5U5zl2TqlHoEv0FbgsNqSTo2PmRfbeWaBQ5ZcLkt0m/pk
yRxD6W6b7nje7fPH9MGDL08u6V7WwARBnQsoKDwoXYhKuM4DY6yY8C0DPDbsnP0i9Wwkr01TK+eJ
UKFQPW+MCVmPbh1x7O7WUzyed0WHEjUjO+kc8/QRH4uV7GMYYqCEVW9KFoTeSKGNhgoRgTJKCHq2
TSz60EjuHBuZzzydhNOgPENu4yjWBgsDkDWv51scTzStee2qukYPvYnVJiMRUFrfFg6kWQqYhJDP
w8ym9uxzuEVgZroYWmn+ds4zYVtrV3tF55jBwAD42sizPVBYmUGOGNQRmCLTRAw6n0UdH3KVFUcb
QCjVwYg+jKcI1HbZOsYBngmRbWaTSSwrU8Kj6pJpkbRvVASARqOreas0PQe7peOeufiBszfyZ5/P
f34koFydb9Nk9yMBs0GVVBmHpsNuv8Nw6/xcxuKEzhm64mKSOzP6cA1aTbrtkq/xMg36UdB3G8oK
OnttMc7F2ZvXi7nzldcfzx7tvvvo9p2v7K9CFeQ6xr6sS4UXBNejqaVDsX4bjQ902aPP47uNrfZw
yi2QsTl34tKDD46gtWAt9IXWpmyDclvNl5uTfI44gINUFfCXkqoV2KD9CgBb0PXdizMONYyK1+8A
abhSMH/J0RkZcLE13B6R5fyXCkLfrDaNUHBH9XLFRT8k4seoVNe6Z+Z1xC9fe090GtE+o7lk+ChG
yk2s7vV7/IcOFd8Amf/SO0aF0L1n6QfmutxmhL7AZKEsd8by9DbMawTDnVHzdzfbgaZMuu8UIrrv
UZzUagfwMt259blC+ui+x/Cy++4A3eXkb9Uef09Pff05qbuEKjGQH3bHimCX6+3fi+zs5LBf7Q6h
QEm7I9dXb7qv6br6KeGrquZJjId0SY/O4QXqCcseWyPLw+MX53AJLwjw32yiJt44moSeo8ZBZEXO
xItGU2VPvIDuNDqu+AKw6/xOZSgPdiS2lvw10qFbrHRPNi5YHvZ4SHdVf9bXBDer8fqY7uokJ3Yc
y3Jt26GBq5PLHVGF+S2zsj+IoXhXnQgXWVXtLLyOKSD842JHRnsU4JVa0l22MPhQxnvW0bkQ6tJd
TLq4DIJXu8a5zda3XIx1L9uSiOKlvoSrL2HyNSMGicchy4gCWui3Fz7Jjst1Uec84PLAMnyi83jH
TFg2bneoVPAGcrtlo42xJeefVLNdXvFRynbDr7/+D8ykyeA=
===END CRASH DUMP===

**Comment by xXNiceYT** [comment]
Thanks, I’ll be looking into it right now.
