### ISSUE TITLE
Hey help me 2

### ISSUE THREAD

**Issue by MrNinja008** [CLADevs/VanillaX#30]
Yes I Thought it was my plugins issue and then i tried the plugin in my test server i have only one plugin that is vanillaX in My Test server and there if i break block it doesn't drop...

**Comment by xXNiceYT** [comment]
Did you use the lastest version it fixed some issues with nether rite shovel. Other than that I could break blocks fine in my world

**Comment by MrNinja008** [comment]
> Did you use the lastest version it fixed some issues with nether rite shovel. Other than that I could break blocks fine in my world

Ok let me check it out

**Comment by xXNiceYT** [comment]
alright

**Comment by xXNiceYT** [comment]
If new version doesn’t work. It could be your gamerule, thats last thing that could’ve cause that. If doTileDrops is false, any blocks drop would not work

**Comment by MrNinja008** [comment]
> If new version doesn’t work. It could be your gamerule, thats last thing that could’ve cause that. If doTileDrops is false, any blocks drop would not work

It doesn't work can i dm you in discord?

**Comment by xXNiceYT** [comment]
Hm I’ll retry again once I get home
