### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Altamash347** [CLADevs/VanillaX#33]
Does this plugin has Enderdragon?

**Comment by xXNiceYT** [comment]
It does have every mcpe entities, just not the functionality such as movement, attack, etc.

**Comment by Altamash347** [comment]
> It does have every mcpe entities, just not the functionality such as movement, attack, etc.

Does it have enderdragon? I just need a statue of Enderdragon

**Comment by xXNiceYT** [comment]
Yes it does.
