### ISSUE TITLE
Excellent Plugin

### ISSUE THREAD

**Issue by Jesnaes** [CLADevs/VanillaX#36]
Hello, I found your Plugin, it's great, it's a very good job, I just have 2 errors

1. When breaking a block does not drop, the block disappears.
2. No fall damage

**Comment by xXNiceYT** [comment]
Check your gamerule, it’s likely them. Type /gamerule 
And check if fallDamage is true if so it will cancel fall damages
and your breaking issue should be one of game rule too
Make sure doTileDrops is on for it to drops blocks if not it will not drop blocks

**Comment by xXNiceYT** [comment]
If those doesn’t work, could you tell me how I could reproduce it? For me fall damage and breaking seems fine hm might be something with your server
