### ISSUE TITLE
Can you add 1.16 Items?

### ISSUE THREAD

**Issue by strich3** [CLADevs/VanillaX#4]
Can you add the 1.16 items?

**Comment by xXNiceYT** [comment]
Yes

**Comment by strich3** [comment]
OMG Thx!

**Comment by xXNiceYT** [comment]
Could you list the items you want?

**Comment by xXNiceYT** [comment]
Well I could add all of 1.16 but some items aren’t possible in pocketmine 3.0

**Comment by AIPTU3110** [comment]
> Well I could add all of 1.16 but some items aren’t possible in pocketmine 3.0

Suggestion to added vanilla commands like https://github.com/DenielWorld/VanillaCommands but use extends \pocketmine\command\defaults\VanillaCommand and permission pocketmine.command.*

**Comment by xXNiceYT** [comment]
> > Well I could add all of 1.16 but some items aren’t possible in pocketmine 3.0
> 
> Suggestion to added vanilla commands like https://github.com/DenielWorld/VanillaCommands but use extends \pocketmine\command\defaults\VanillaCommand and permission pocketmine.command.*

Vanilla commands are coming soon
