### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DumbChester** [CLADevs/VanillaX#49]
How to disable a block?

**Comment by xXNiceYT** [comment]
Go to Config.yml

and change from this format
#disabled:
#  #List of blocks that wont be registered
#  blocks:
#    - 145 #This would be anvil block Id

To
disabled:
  #List of blocks that wont be registered
  blocks:
    - 145 #This would be anvil block Id
 
 this blocks anvil change 145 id to whatever id you want to not add

**Comment by DumbChester** [comment]
do you have a list of Blocks you Added? so i can see what would double register if im using other plugins?

**Comment by DumbChester** [comment]
i mean i think you register some blocks even tho they aren't functional yet

**Comment by xXNiceYT** [comment]
It should in readme section and yes I’ve registered blocks which aren’t functional yet lol
