### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#53]
Add Enchanting Table Worked

**Comment by AIPTU** [comment]
Enchanting tablet doesn't work?, Work for me

**Comment by YaNIND** [comment]
![Screenshot_2021-07-07-10-32-26-139_com mojang minecraftpe](https://user-images.githubusercontent.com/84168756/124696331-09fcd480-df0f-11eb-9bb6-8cc5f1ccf27b.jpg)

**Comment by YaNIND** [comment]
![Screenshot_2021-07-07-10-32-18-021_com mojang minecraftpe](https://user-images.githubusercontent.com/84168756/124696443-4c261600-df0f-11eb-98f9-f948f1676c9c.jpg)

**Comment by DumbChester** [comment]
Need more.details like
Minecraft Version
PMMP version
PHP VERSION
other plugins used

How.to reproduce bug etc

IT WORKS fine with me too.

**Comment by YaNIND** [comment]
maybe you using vanillainventory

**Comment by AIPTU** [comment]
No lol

**Comment by YaNIND** [comment]
i use php 7.4 and new pmmp

**Comment by AIPTU** [comment]
Well you are right in the new commit there is no enchanting table, maybe the author forgot

**Comment by xXNiceYT** [comment]
weird those should of been in inventory, ill fix it.
