### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#55]
Brewing Work and Beacon Work

**Comment by YaNIND** [comment]
https://user-images.githubusercontent.com/84168756/125159632-cf12cf00-e1a2-11eb-9411-26450d9a246d.mp4


https://user-images.githubusercontent.com/84168756/125159640-db972780-e1a2-11eb-802f-de45cb4f8934.mp4

**Comment by MonoAdrian23** [comment]
Wow xd
In Pocketmine works nothing. 
Use Powernukkit and you have working Items

**Comment by DumbChester** [comment]
> Wow xd
> In Pocketmine works nothing. 
> Use Powernukkit and you have working Items 

Wow, You are in every Pmmp Plugin Issue/request plugging PowerNukkit, I wonder why?

**Comment by MonoAdrian23** [comment]
Its a wonder xd

**Comment by xXNiceYT** [comment]
Beacon doesnt work yet havent been implemented
