### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by llPushkarSinghll** [CLADevs/VanillaX#65]
https://user-images.githubusercontent.com/84075300/126877973-057ceefc-d9fc-42c4-9860-de8011c7c6db.mp4

Try To add boat , breving stand and beacon also

**Comment by xXNiceYT** [comment]
Hm what enchantments does your slot 1 item has and what enchantments does slot 2 book has?

**Comment by xXNiceYT** [comment]
Also brewing stand should be added

**Comment by YaNIND** [comment]
can't Support with piggycostumenchant bruh

**Comment by xXNiceYT** [comment]
Why wouldn’t it be compatible w piggy ce

**Comment by llPushkarSinghll** [comment]
> Why wouldn’t it be compatible w piggy ce

Thats not that problem , that problem is books are disappearing

**Comment by xXNiceYT** [comment]
> > Why wouldn’t it be compatible w piggy ce
> 
> Thats not that problem , that problem is books are disappearing

Can’t really do anything if you don’t tell me how to cause this issue in my own server lol

**Comment by Lentou** [comment]
PiggyCE have the ability to put CEBooks in some Tools or Armors. Just switch their inventory and then the CE will put in it.

**Comment by xXNiceYT** [comment]
> PiggyCE have the ability to put CEBooks in some Tools or Armors. Just switch their inventory and then the CE will put in it.

If it’s custom enchants, and isnt vanilla then it wouldn’t work, well it would but the lore wouldn’t appear which is important to identify what enchants ur weapon or any equipment has

**Comment by llPushkarSinghll** [comment]
> > PiggyCE have the ability to put CEBooks in some Tools or Armors. Just switch their inventory and then the CE will put in it.
> 
> If it’s custom enchants, and isnt vanilla then it wouldn’t work, well it would but the lore wouldn’t appear which is important to identify what enchants ur weapon or any equipment has

Bruh why u all talking about ce enchantment the problem is that when i put a sword + book in anvil then i replace the book in anvil and the book which is replaced are disappeared

**Comment by xXNiceYT** [comment]
? So how would I cause this?

**Comment by llPushkarSinghll** [comment]
👀

**Comment by llPushkarSinghll** [comment]
Hmm leave it lol
