### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by llPushkarSinghll** [CLADevs/VanillaX#66]
[Mon_Jul_26-18.16.27-WIB_2021.log](https://github.com/CLADevs/VanillaX/files/6877704/Mon_Jul_26-18.16.27-WIB_2021.log)

**Comment by xXNiceYT** [comment]
hm ill check

**Comment by llPushkarSinghll** [comment]
Fix it pls because i want to use name space remover plug-in

**Comment by xXNiceYT** [comment]
Do you have any other plugin that overwrites off hand?

**Comment by llPushkarSinghll** [comment]
> Do you have any other plugin that overwrites off hand?

I don't think so but the error causing with https://poggit.pmmp.io/p/NameSpaceRemover/1.0.0 this plugin

**Comment by xXNiceYT** [comment]
hm, can't seem to reproduce it once again lol 
![image](https://user-images.githubusercontent.com/23722462/127154264-c56b958e-fcd7-4f46-8944-06817a8de983.png)

**Comment by xXNiceYT** [comment]
ima make a check regardless just incase this happens
