### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by callumrawlinson** [CLADevs/VanillaX#7]
I have a mob spawner gui and entity management code if you want. i will send it to you if you need it

**Comment by xXNiceYT** [comment]
Why would I need that? ._.

**Comment by callumrawlinson** [comment]
Check your to do

**Comment by xXNiceYT** [comment]
There is no need for  mob spawner gui lol

**Comment by callumrawlinson** [comment]
ok :) just trying to help
