### ISSUE TITLE
Trident Error

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#70]
when you throw the trident and left the server make crash

**Comment by xXNiceYT** [comment]
What does it say? The error

**Comment by YaNIND** [comment]
Trident Entity Not Registed

**Comment by xXNiceYT** [comment]
Can you send the error perhaps?

**Comment by YaNIND** [comment]
[Wed_Jul_28-00.02.05-WIB_2021.log](https://github.com/CLADevs/VanillaX/files/6899691/Wed_Jul_28-00.02.05-WIB_2021.log)
