### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#78]
![IMG-20210731-WA0447](https://user-images.githubusercontent.com/84168756/127736898-cf3a2eed-83b0-4f3d-ad7a-23db4fbea414.jpg)

**Comment by AIPTU** [comment]
Try restarting the server

**Comment by AGTHARN** [comment]
oui oui baguette 🥖

**Comment by xXNiceYT** [comment]
Weird try downloading new phar from poggit again and try it in ur server
