### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jaylac2000** [CLADevs/VanillaX#8]
config to enable/disable certain things, entities or items - this will make the plugin great for if someone else has something else in here enabled in a different plugin or way

also add redstone items (maybe from RedStoneX) - this plugin will be great for a creative server that this point - or very few items that can be enabled on server without dupe bugs/glitches

**Comment by xXNiceYT** [comment]
Yeah I am thinking of doing this after I have done some other stuff.
