### ISSUE TITLE
Block/Mob Drop Issue

### ISSUE THREAD

**Issue by ElectroGamesYT** [CLADevs/VanillaX#82]
This plugin causes blocks and mobs to not drop anything.

**Comment by xXNiceYT** [comment]
Might be one of your gamerule is disabled/enabled which allows entities drop or block drops

**Comment by ElectroGamesYT** [comment]
Unless its true by default, I never touched gamerules.

**Comment by xXNiceYT** [comment]
Can you type /gamerule and send a picture here?

**Comment by YaNIND** [comment]
Turn On Is Off by default plugins

**Comment by xXNiceYT** [comment]
Weird, it should be on I’ll check once I get home.

**Comment by xXNiceYT** [comment]
Tested it using latest version, seems to work fine for me.
