### ISSUE TITLE
COMPATIBLE WITH PURE ENTITIES X?

### ISSUE THREAD

**Issue by MadooxMc** [CLADevs/VanillaX#86]
I have reed the mobs of your plugin comport armor etc… is compatible with pure entities X? If i have pure entities X in my servor, the mobs of your plugin will work or, i i ve got to remove pure entities x?

**Comment by xXNiceYT** [comment]
In Config you can turn off mobs but it also disables all entities that includes armor stand, another way would be to add the entities you want pure entities to register within “mobs” section at disable part just uncomment(removing #) those commented message

**Comment by xXNiceYT** [comment]
This is what it looks like on Config
```#disabled:
#  #Mobs includes armor stand, zombies, etc.
#  mobs:
#    - 43 #this would be blaze entity Id
```
Let say you want to disable blaze it would be

```

disabled:
  #Mobs includes armor stand, zombies, etc.
  mobs:
    - 43 #this would be blaze entity Id
``` replacing previous code with this should disable VanillaX blaze but it lets u register pure entities one

ids can be found on https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/entity/EntityIds.php#L61


You can’t use names to disable entities unfortunately, it will be added in 4.0 tho
