### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#89]
- add smithing tabble
- add nether portal working
- add vanillablocks

**Comment by YaNIND** [comment]
How to craft netherite armor?

**Comment by AIPTU** [comment]
Honestly it's not that easy to add some blocks in PM3 because of limited mapping

**Comment by xXNiceYT** [comment]
^^ as for now I won’t be adding anymore till 4.0 arrives, I’ve been adding new block in 4.0 branch tho

**Comment by YaNIND** [comment]
how to craft netherite armor

**Comment by xXNiceYT** [comment]
i might of forgotten to add that, adding it

**Comment by xXNiceYT** [comment]
it has been added
