### ISSUE TITLE
Help me please if you can !!🥺

### ISSUE THREAD

**Issue by MadooxMc** [CLADevs/VanillaX#92]
Please i don’t know any devloper, i don’t understand why a plugin work in my server, this plugin is mycrate, and when i share the plugin with other player, ther can’t use, this crash them server, but i even shared my invcrashfix and invmenu plugins but nothing to do they still come across this error yet the plugin works very well for me and we have the same pocketmine version… that’s error, Error: "Class 'Ds\Queue' not found" (EXCEPTION) in "plugins/MyCrate_v1.0.0 Beta.phar/src/VirakMC/MyCrate/libs/muqsit/invmenu/session/ if you can help me, i don’t understand why other player can’t be put this plugin without have crash server ….. i know you are not support but your help would be welcome, or just one suggestion, a lead that could enlighten me

**Comment by xXNiceYT** [comment]
Idk man, it’s unrelated tho

**Comment by MadooxMc** [comment]
I know , sorry bro

**Comment by MrNinja008** [comment]
@MadooxMc you need to update invmenu virion of the plugin

**Comment by MrNinja008** [comment]
Can you able to share this plug-in github link? @MadooxMc
