### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YaNIND** [CLADevs/VanillaX#93]
use bedrock data https://github.com/supercrafter333/BedrockData
to add 1.17 items or block? its working or not? supercrafter333 added 1.17 blocks or  item mapping

**Comment by xXNiceYT** [comment]
I will not be adding new blocks nor any items that is related to 1.17 within 3.0 api, its being added within 4.0. I know some people done it but it will break in the feature, your block will not remain the same if you are using 3.0 and have 1.17 blocks

**Comment by YaNIND** [comment]
oh okay thanks for answer
