### ISSUE TITLE
Inventory Stuck

### ISSUE THREAD

**Issue by NubDevvx** [CLADevs/VanillaX#94]
I found a bug in this plugin, after I installed the vanillax plugin the items in my inventory were often stuck, examples like elyta, beacon, echnated book were all stuck and couldn't be moved, please fix it immediately

**Comment by xXNiceYT** [comment]
It seems to be fine for me?

**Comment by NubDevvx** [comment]
> It seems to be fine for me?

try to drop 2 totems at the same time then pick them up
