### ISSUE TITLE
Redstone not work

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#96]
Hi, i have one bug with vanilla X , when I start my server, redstone not work, i try to add redstone circuit but with vanilla X they have conflicts and if y disable and enable another redstone circuit (i used plugin servertools for disable and enable) the redstone work but when I restart my server, i have the same issue and i must disable and enable redstone circuit to work :/

**Comment by xXNiceYT** [comment]
Well thing was I was suppose to add my own redstone system but had no availability so I haven’t done them. I will add a Config toggle system for redstone just in case

**Comment by xXNiceYT** [comment]
Nvm ima just disable redstone atm
