### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SPMP2** [CLADevs/VanillaX#97]
Hi, i have a bug with version after 109 (dev 109 work good but not redstone fix) with dev 111 and 112 i think, my plugin 1vsBOT is disable when i start my server, if i activate with servertools, this plugin work but when i restart my server, this plugin are another disable .. is not a big problem but it’s strange

**Comment by xXNiceYT** [comment]
Is there any errors?

**Comment by SPMP2** [comment]
How no i m sorry this is just with 111, dev 112 work fine !!  Thank’s very mutch
